### ISSUE TITLE
Need to explicitly call detectChanges with host

### ISSUE THREAD

**Issue by jpzwarte** [NetanelBasal/spectator#102]
```typescript
      host.setInput('disabled', true);
      host.detectChanges();

      expect(host.element).toHaveClass('icl-drop-zone-disabled');
```

My understanding is that when i call `setInput`, it automatically calls `detectChanges`. But if i remove the 2nd line above, the test fails. This only happens with `SpectatorWithHost`.

**Comment by NetanelBasal** [comment]
It depends on the use-case. It can call it on the host or the component. https://github.com/NetanelBasal/spectator/blob/master/projects/spectator/src/lib/internals.ts#L57

I can't tell what's your case.

**Comment by jpzwarte** [comment]
```typescript
const createHost = createHostComponentFactory(DropZoneComponent);

host = createHost(`<icl-drop-zone></icl-drop-zone>`);
```

Does that help?

**Comment by NetanelBasal** [comment]
It calls https://github.com/NetanelBasal/spectator/blob/master/projects/spectator/src/lib/internals.ts#L50 which is the host, which I guess it what you need. The `setInput` invoke the `detectChanges` method on the tested component.

**Comment by jpzwarte** [comment]
Ok, so works as designed? Or is there something that can be improved here? :)

**Comment by NetanelBasal** [comment]
Yes, it works as expected. It's confusing sometimes, but that's how Angular works. You have the host and the component itself. We can add a third parameter to `setInput`, but I can't see any benefit for this.

**Comment by NetanelBasal** [comment]
Something like:
`host.setInput('disabled', true, { hostDetectChanges: true });`

**Comment by jpzwarte** [comment]
Nah, that feels overkill.
