### ISSUE TITLE
Mouse event helpers missing features

### ISSUE THREAD

**Issue by jsantha** [NetanelBasal/spectator#105]
Event object helpers for creating mouse events miss following features:

- event bubbling
- specifying mouse event button

Quick look at current implementation of Angular CDK library mouse event helpers shows that there is enabled event bubbling by default and you can explicitly specify a mouse button.

**Spectator:**
https://github.com/NetanelBasal/spectator/blob/master/projects/spectator/src/lib/event-objects.ts#L4

**CDK testing**
https://github.com/angular/components/blob/master/src/cdk/testing/event-objects.ts#L10

**Comment by jsantha** [comment]
We need this line as well: 
https://github.com/angular/components/blob/master/src/cdk/testing/event-objects.ts#L31

Otherwise the **mouseenter** event is considered fake, see:
https://github.com/angular/components/blob/master/src/cdk/a11y/fake-mousedown.ts

**Comment by NetanelBasal** [comment]
Done.
