### ISSUE TITLE
Fix JQuery Npm Audit Vulnerability

### ISSUE THREAD

**Issue by rogerza** [NetanelBasal/spectator#107]
Update to jquery 3.4.0 needed to patch this vulnerability.

[www.npmjs.com/advisories/796](https://www.npmjs.com/advisories/796)

![image](https://user-images.githubusercontent.com/2261336/57735350-e52bb000-7669-11e9-916b-faa43d8d1d3e.png)

**Comment by askarby** [comment]
I've attempted to bump the version of jQuery to 3.4.1.

The PR can be found here: https://github.com/NetanelBasal/spectator/pull/108

When running `npm test` all tests passes, but `npm start` is not able to bring up the example application (I'm doubting that I have anything to do with that).
