### ISSUE TITLE
Bumping version 3.8.1 but still getting jquery 3.3.1

### ISSUE THREAD

**Issue by Lavioli** [NetanelBasal/spectator#109]
After updating to 3.8.1 and reinstalling, I am seeing the dependency for jQuery is still 3.3.1. 
![Screen Shot 2019-05-15 at 10 15 34 AM](https://user-images.githubusercontent.com/17465323/57787296-b4e02200-76fa-11e9-94f5-95811f31792d.png)

**Comment by Lavioli** [comment]
Have tried `npm ci`, deleting node_modules folder and reinstalling. the jquery dependency is still showing 3.3.1

**Comment by benelliott** [comment]
The version number needs to be updated here: https://github.com/NetanelBasal/spectator/blob/master/projects/spectator/package.json#L27

**Comment by NetanelBasal** [comment]
Yes, on it.

**Comment by NetanelBasal** [comment]
Fixed in v3.8.2

**Comment by Lavioli** [comment]
Thank you :)
