### ISSUE TITLE
Could it work with Jest?

### ISSUE THREAD

**Issue by slawojstanislawski** [NetanelBasal/spectator#11]
I would like to use this library with Jest testing framework, however when I follow the instructions provided on this repo https://github.com/thymikee/jest-preset-angular I'm getting errors: 
`Cannot read property 'hostFixture'/'testedComponent'/'create'  of null`.

**Comment by bengry** [comment]
Can you repro this on a sample repo by any chance? I use it on a project of
mine at work with Jest and it works fine.

**Comment by NetanelBasal** [comment]
In general, It supports jasmine, but @bengry says it is working with jest, so maybe he can help.

**Comment by slawojstanislawski** [comment]
I've been using the library since it came out under a different name, and it used `function(this: Context)`, I didn't notice the change to arrow functions. Now I checked and in fact it's working fine with jest. Awesome library btw.

**Comment by NetanelBasal** [comment]
Thanks :)

**Comment by LayZeeDK** [comment]
#40 added a Jest API to version 2.3.0.
