### ISSUE TITLE
How to generate mouse click on element?

### ISSUE THREAD

**Issue by antonpegov** [NetanelBasal/spectator#115]
Without Spectator it was:
>     spyOn(component.hideSection, 'emit');
>     const button = debugElement.query(By.css('.btn-link'));
>     button.nativeElement.click();
>     expect(component.hideSection.emit).toHaveBeenCalledTimes(1);

Now, with Spectator It not working anymore:
>      spyOn(spectator.component.hideSection, 'emit');
>      const button = spectator.query('.btn-link');
>      button.[WHAT IS HERE?].click();
>      expect(spectator.component.hideSection.emit).toHaveBeenCalledTimes(1);

**Comment by benelliott** [comment]
Try `spectator('.btn-link').click()` or `spectator(button).click()`.

Please can you read [the documentation](https://netbasal.gitbook.io/spectator/) before opening an issue? It includes a lot of examples.

**Comment by antonpegov** [comment]
@benelliott I did. Try to enter "spectator.click" in the search and you will see nothing. The documentation is really unfriendly to newcomers.

**Comment by benelliott** [comment]
Sorry to hear that, although it does come up when you search for "click". Suggestions for improving the docs are welcomed.
