### ISSUE TITLE
fix(spectator): loosen type restrictions on Spectator.get

### ISSUE THREAD

**Issue by glackk** [NetanelBasal/spectator#116]
The TypeScript definition on Spectator.get doesn't allow type `any`, which is more restrictive than the wrapped `TestBed.get` (e.g. cannot use abstract classes).  The issue and fix are likely similar to [PR48](https://github.com/NetanelBasal/spectator/pull/48).

**Comment by benelliott** [comment]
Could you provide a code snippet to show what you mean?

**Comment by glackk** [comment]
Sure.  Here's a small example:
```
import { MyAbstractService } from '@foo/bar';
import { Spectator, createTestComponentFactory } from '@netbasal/spectator/jest';

describe('MyComponent', () => {

  let spectator = Spectator<MyCompoennt>;

  const createComponent = createTestComponentFactory({
    component: MyComponent,
  });

  beforeEach(() => {
    spectator = createComponent();
  });

  it('should do something cool', () => {
    const myService = spectator.get<MyAbstractService>(MyAbstractService, true); //error here
    spyOn(myService, 'doOther');
    spectator.component.doSomething();
    expect(myService.doOther).toHaveBeenCalled();
  });

});
```
The error occurs on the first line of the actual test with 'spectator.get'. 

> Argument of type 'typeof MyAbstractService' is not assignable to parameter of type 'Type\<MyAbstractService\> | InjectionToken\<MyAbstractService\>'.

> Cannot assign an abstract constructor type to a non-abstract constructor type.

**Comment by NetanelBasal** [comment]
@dirkluijk your PR takes care of this issue?

**Comment by dirkluijk** [comment]
Yes!
