### ISSUE TITLE
Support needed. Test service call in ngOnInit of component

### ISSUE THREAD

**Issue by tobang** [NetanelBasal/spectator#117]
I have just switched to testing with Spectator and Jest. I am trying to test if a service function is called during ngOnInit. It is just a simple utility service without any http calls.

On the component I have the following:
.....
 @Input() arrangement: Arrangement;

  public valgForm: FormGroup;

  constructor(private vcs: ValgControlService) {}

  ngOnInit() {
    this.valgForm = this.vcs.toFormGroup(this.arrangement.Valg);
  }
........

Now i wish to test if the toFormGroup function was called during ngOnit. Here is my current spec:

import {
  SpectatorWithHost,
  createHostComponentFactory,
  SpyObject
} from "@netbasal/spectator/jest";
import { FormsModule, ReactiveFormsModule } from "@angular/forms";

import { MatCheckboxModule } from "@angular/material/checkbox";

import { Arrangement } from "../../state/types/arrangement.type";
import { ValgComponent } from "./valg.component";
import { ValgItemComponent } from "./valg-item/valg-item.component";
import { MatFormFieldModule } from "@angular/material/form-field";
import { ValgControlService } from "./valg.control.service";

function createArrangement(): Arrangement {
  return {
    Id: "1",
    Name: "Onsdagsmotion - Beach Volley",
    Number: "201900006051",
    RegistrationDeadline: "2019-05-29T22:00:00Z",
    CancellationDeadline: "2019-05-29T22:00:00Z",
    Valg: [
      {
        Id: "2",
        Name: "Vil du have frokost?",
        Valglinjer: [
          {
            Id: "3",
            Name: "Ja tak",
            Price: 0.0
          }
        ]
      }
    ]
  };
}

describe("ValgComponent", () => {
  let vcs: SpyObject<ValgControlService>;
  let host: SpectatorWithHost<ValgComponent>;

  const createHost = createHostComponentFactory({
    component: ValgComponent,
    declarations: [ValgItemComponent],
    imports: [
      FormsModule,
      ReactiveFormsModule,
      MatCheckboxModule,
      MatFormFieldModule
    ],
    providers: [],
    mocks: [ValgControlService],
    shallow: true
  });
  const arr = { arrangement: createArrangement() };
  beforeEach(() => {
    host = createHost(`<dgi-valg></dgi-valg>`, true, arr);
    vcs = host.get<ValgControlService>(ValgControlService);
  });

  it("should exist", () => {
    expect(host.component).toBeDefined();
  });

  it("should have called toFormGroup", () => {
    host.component.ngOnInit();
    expect(vcs.toFormGroup).toHaveBeenCalledWith(arr.arrangement.Valg);
  });
});

The test fails. Any help appreciated. Thanks.

**Comment by benelliott** [comment]
Hi, please could you format your code using three backticks so it's readable?

`````````
```
Like this
```
`````````

**Comment by tobang** [comment]
Oh, sorry

```
@input() arrangement: Arrangement;

public valgForm: FormGroup;

constructor(private vcs: ValgControlService) {}

ngOnInit() {
this.valgForm = this.vcs.toFormGroup(this.arrangement.Valg);
}
```
```
import {
  SpectatorWithHost,
  createHostComponentFactory,
  SpyObject
} from "@netbasal/spectator/jest";
import { FormsModule, ReactiveFormsModule } from "@angular/forms";

import { MatCheckboxModule } from "@angular/material/checkbox";

import { Arrangement } from "../../state/types/arrangement.type";
import { ValgComponent } from "./valg.component";
import { ValgItemComponent } from "./valg-item/valg-item.component";
import { MatFormFieldModule } from "@angular/material/form-field";
import { ValgControlService } from "./valg.control.service";

function createArrangement(): Arrangement {
  return {
    Id: "1",
    Name: "Onsdagsmotion - Beach Volley",
    Number: "201900006051",
    RegistrationDeadline: "2019-05-29T22:00:00Z",
    CancellationDeadline: "2019-05-29T22:00:00Z",
    Valg: [
      {
        Id: "2",
        Name: "Vil du have frokost?",
        Valglinjer: [
          {
            Id: "3",
            Name: "Ja tak",
            Price: 0.0
          }
        ]
      }
    ]
  };
}

describe("ValgComponent", () => {
  let vcs: SpyObject<ValgControlService>;
  let host: SpectatorWithHost<ValgComponent>;

  const createHost = createHostComponentFactory({
    component: ValgComponent,
    declarations: [ValgItemComponent],
    imports: [
      FormsModule,
      ReactiveFormsModule,
      MatCheckboxModule,
      MatFormFieldModule
    ],
    providers: [],
    mocks: [ValgControlService],
    shallow: true
  });
  const arr = { arrangement: createArrangement() };
  beforeEach(() => {
    host = createHost(`<dgi-valg></dgi-valg>`, true, arr);
    vcs = host.get<ValgControlService>(ValgControlService);
  });

  it("should exist", () => {
    expect(host.component).toBeDefined();
  });

  it("should have called toFormGroup", () => {
    host.component.ngOnInit();
    expect(vcs.toFormGroup).toHaveBeenCalledWith(arr.arrangement.Valg);
  });
});

```

**Comment by benelliott** [comment]
Hmm... nothing is jumping out at me so far. Please could you provide the full source of your `dgi-valg` component including its decorator, along with the error message in the test failure?

**Comment by tobang** [comment]
Solved the issue myself with this test:

```
 it("should call toFormGroup", () => {
    const getFormGroupSpy = spyOn((host.component as any).vcs, "toFormGroup");
    host.component.ngOnInit();
    expect(getFormGroupSpy).toHaveBeenCalled();
  });
```
Thank, for your time.

**Comment by benelliott** [comment]
Ah yes - you were providing a mock of `ValgControlService` but must create a spy in order to test whether its methods have been called.
