### ISSUE TITLE
Add other HTTP methods to Enum

### ISSUE THREAD

**Issue by DuncanFaulkner** [NetanelBasal/spectator#118]
I've started to use Spectator recently after reading an article by Wes Copeland and it has helped me be able to test services in my Angular app.

I recently hit an issue in that the application I'm writing tests for uses PATCH (rather than PUT).
I was going to try and add this myself and do a PR for it but at the moment. I'm not able to build the project, fails on npm i (looks something to do with node and node-sass, but need to look into it).

In the meantime is it possible to add to the following enum in the http file:

export declare enum HTTPMethod {
  GET = 'GET',
  POST = 'POST',
  DELETE = 'DELETE',
  PUT = 'PUT',
  PATCH = 'PATCH'  // <---- this one    
}

Cheers

**Comment by benelliott** [comment]
Note: also missing HEAD, OPTIONS, (JSONP?)

**Comment by NetanelBasal** [comment]
`as any` should work for now.

**Comment by NetanelBasal** [comment]
Added in the latest version. https://github.com/NetanelBasal/spectator/commit/b608473c7cc671cb1e7a0e71531619faf3353676
