### ISSUE TITLE
README files are out of sync

### ISSUE THREAD

**Issue by LayZeeDK** [NetanelBasal/spectator#119]
[`/README.md`](https://github.com/NetanelBasal/spectator/blob/b608473c7cc671cb1e7a0e71531619faf3353676/README.md) and [`/projects/spectator/README.md`](https://github.com/NetanelBasal/spectator/blob/b608473c7cc671cb1e7a0e71531619faf3353676/projects/spectator/README.md) are out of sync.

Can we just delete the latter one and make sure to copy and bundle the one in the root project directory?

**Comment by NetanelBasal** [comment]
Done. Thanks.
