### ISSUE TITLE
Project isn't aligned with its own set standards

### ISSUE THREAD

**Issue by bengry** [NetanelBasal/spectator#12]
The code is mentioned to be formatted using Prettier, and uses TSLint. However, the code within it is not conforming to the latter, and the use of Prettier's formatting isn't automatic via a pre-commit hook.

**Comment by NetanelBasal** [comment]
https://github.com/NetanelBasal/spectator/blob/master/package.json#L27

**Comment by NetanelBasal** [comment]
Closing as it's working as expected.

**Comment by bengry** [comment]
@NetanelBasal Some file ([example](https://github.com/NetanelBasal/spectator/blob/master/src/app/zippy/zippy.component.ts)) aren't aligned with the Prettier configuration. Am I missing something?
