### ISSUE TITLE
Multiple lockfiles

### ISSUE THREAD

**Issue by LayZeeDK** [NetanelBasal/spectator#120]
We have both [`package-lock.json`](https://github.com/NetanelBasal/spectator/blob/b608473c7cc671cb1e7a0e71531619faf3353676/package-lock.json) and [`yarn.lock`](https://github.com/NetanelBasal/spectator/blob/b608473c7cc671cb1e7a0e71531619faf3353676/yarn.lock) lockfiles.

This is a recipe for disaster as it can lead contributors to get out of sync depending on which package manager they use.

At this point, the lockfiles themselves are even out of sync.

Which lockfile do we use, going forward?

**Comment by NetanelBasal** [comment]
We will go with npm. Thanks.
