### ISSUE TITLE
[question]: How to mock service in the "mocks" parameter in createTestComponentFactory?

### ISSUE THREAD

**Issue by joshiraez** [NetanelBasal/spectator#125]
Hi.

I have a component that, onInit, will try to subscribe to a repository observable.

I have found that, inside "providers", I can use the "mockProvider" function and pass on my mocked functions behaviours. Plus, this is done before even creating the component, so I can let automatic change detection to true.

Is there any way to do this using the "mocks" parameter? Is to allow everyone to always use the same parameters for all mocks in the system.

Because "mocks" doesn't allow to set up a mock, i'm forced to set detect changes to false and manually launch detect changes on every event update :/

The below 2 test work. What I want is to be able to set up "mocks" like I set up "providers".

```

  let spectator: Spectator<OrderHistoryComponent>;
  const createComponent = createTestComponentFactory({
    component: OrderHistoryComponent,
    declarations: [MockComponent(OrderHistoryListComponent)],
    mocks: [OrderHistoryRepository],
    detectChanges: false
  });

  beforeEach(()=> {
    spectator= createComponent()
    spectator.get<OrderHistoryRepository>(OrderHistoryRepository).getProductList.and.returnValue(of(EXPECTED_ORDER_HISTORY))
    spectator.detectChanges()
  })

  it('should create', () => {    
    expect(spectator.component).toBeTruthy();
  });
```

```
  let spectator: Spectator<OrderHistoryComponent>;
  const createComponent = createTestComponentFactory({
    component: OrderHistoryComponent,
    declarations: [MockComponent(OrderHistoryListComponent)],
    providers: [mockProvider(OrderHistoryRepository, {getProductList: () => of(EXPECTED_ORDER_HISTORY)})]
    });

  it('should create', () => {    
    spectator = createComponent()

    expect(spectator.component).toBeTruthy();
  });
```

The problematic ngOnInit code is this btw:

```
@Component({
  selector: 'app-order-history',
  templateUrl: './order-history.component.html',
  styleUrls: ['./order-history.component.scss']
})
export class OrderHistoryComponent implements OnInit {

  constructor(private _service: OrderHistoryRepository) { }

  order: IOrderHistory;

  ngOnInit() {
    this._service
      .getProductList()
      .subscribe( next => this.order = next );
  }

}
```
Yeah, is a simple component. And I suspect that this can happen with ngOnInit, ngOnChange and others lifecycle methods as well.

I don't know if there is some way to pass custom mock to the "mocks" parameter that I haven't found. If there isn't, I think it would be a good idea to allow passing the mock as parameter like the "mockProvider" does

**Comment by benelliott** [comment]
Hi, as you mentioned you can do this using `providers`. This is not possible using `mocks` because it is just a shortcut for creating mocks that are simple spies of the classes provided. Adding support for this would probably bloat the API for the `mocks` property enough as to make it pointless.

If you want to use the same API in both cases, you could use `providers: [mockProvider(...)]` even when using simple spy mocks.

**Comment by joshiraez** [comment]
Yeah, that as much as I discovered. I guess that if you want to keep it separate like that, its ok. Thank you for the answer

Btw, do you accept PR's for documentation?

**Comment by benelliott** [comment]
Unfortunately the documentation is not hosted on Github - not sure if @NetanelBasal has a process for this?

**Comment by NetanelBasal** [comment]
It's currently hosted in Gitbook. We should migrate it to Github Wiki so that other developers could contribute.

**Comment by benelliott** [comment]
I like Gitbook for consuming the docs - maybe we could use something like https://docs.gitbook.com/integrations/github so the source of truth is Github but the docs are still readable through Gitbook.

**Comment by NetanelBasal** [comment]
Thanks. I will check it out.
