### ISSUE TITLE
Schematics styleext not works as described (fix included)

### ISSUE THREAD

**Issue by jakubjosef** [NetanelBasal/spectator#126]
Hi,
I found a small problem during integrating spectator schematics to our project.

We using SCSS and when I used code snippet from README with
```
      "schematics": {
        "@netbasal/spectator:component": {
          "style": "scss"
        }
```

It was not working. And it's because we generating components with `ng g cs` and `cs` is shorthand for `spectator-component`, that means we needed to use this code instead
```
    "@netbasal/spectator:spectator-component": {
          "styleext": "scss",
          "changeDetection": "OnPush"
        },
```

Please update a README.

Also I need to say we expected this schematics will extend default `ng g c` command, using different command is a little bit tricky because we need to spread the knowledge across our team. I understand it's maybe not possible to override default targets like `component` I just sharing our thoughts about this.

Thanks in advance.

**Comment by NetanelBasal** [comment]
Unfortunately, this is not currently possible. We'll update the README, thanks.

**Comment by shastaxc** [comment]
This no longer works. `"styleext": "scss"` should now be `"style": "scss"` and README needs to be updated to reflect that.

**Comment by NetanelBasal** [comment]
Thanks, @shastaxc. You're welcome to submit a PR.
