### ISSUE TITLE
feat: easier API for tests involving HttpClient

### ISSUE THREAD

**Issue by LayZeeDK** [NetanelBasal/spectator#129]
Like recent discussions on tests involving the router, we could consider whether we could create an easier testing API for HttpClient. 

https://angular.io/guide/http#testing-http-requests

**Comment by NetanelBasal** [comment]
https://netbasal.gitbook.io/spectator/services/data-services

**Comment by LayZeeDK** [comment]
I completely missed that. My apologies 😅 I may revisit this and see how it stacks up when compared against the vanilla Angular test examples.
