### ISSUE TITLE
[Question]: Interceptor testing

### ISSUE THREAD

**Issue by timwright35** [NetanelBasal/spectator#130]
I have a series of interceptors in my system that each do something different. One caches data, one changes the url, one formats data etc. I am trying to test them using your system but the example does not really show the best way to hit the intercept function with a request and then see what the modified url/data is. It seems we have to mock the handle function and thus the intercept logic never runs.

Could we get better examples on how to use this testing framework for all types of interceptor systems and logic?

Sample of what I have (At the moment trying to just see if the function is called but I want to be able to see if the version number changed in the url as well):
```
describe('DDHttpInterceptor', () => {
  const spectator = createService({
    service: DDHttpInterceptor,
    mocks: [],
    providers: []
  });

  const url = 'http://devlv.cbwsoft.com/v01/api';

  const apiDummyRequest = new HttpRequest('GET', url, {
    headers: new HttpHeaders({
      'use-api-version': '2'
    })
  });

  // TODO(Tim): Figure out how to interrogate the intercept response right.
  it('should detect and change api version', () => {
    [200].forEach((status) => {
      const apiChangeSpy = spyOn(spectator.service, 'modifyUrlApi').and.callThrough();
      spectator.service.intercept(apiDummyRequest, {
        handle: () => of(new HttpResponse())
      }).subscribe();
      expect(apiChangeSpy).toHaveBeenCalled();
    });
  });
});
```

**Comment by LayZeeDK** [comment]
Hi Tim,

If you change your `next` handler in the test, you should be able to verify properties of the processed response.

```typescript
it('should detect and change api version', done => { // <-- Async Jasmine test using `done`
  [200].forEach((status) => {
    const apiChangeSpy = spyOn(spectator.service, 'modifyUrlApi').and.callThrough();
    spectator.service.intercept(apiDummyRequest, {
      handle: request => { // <-- Assert on the processed request in the `next` handler
        expect(request.url.endsWith('v02/api')
		done();

        return of(new HttpResponse());
      },
    }).subscribe();
  });
});
```

**Comment by timwright35** [comment]
Thanks!
