### ISSUE TITLE
[jest] it.each type conflict

### ISSUE THREAD

**Issue by GregOnNet** [NetanelBasal/spectator#131]
Hi @NetanelBasal,

thank you for providing `spectator` I am a big fan of the API you have created.
I tried your library and it seems that some type-definitions of `spectator` still override jest's type definitions.

Importing `@netbasal/spector/jest` causes a compiler error when `it.each` is used.

I prepared a repository reproducing this behaviour: 

- git clone https://github.com/GregOnNet/spectator-jest-playground
- cd spectator-jest-playground
- yarn
- visit `src/app/app.component.spec.ts`

Please let me know if I can provide further information

Thanks in advance
Gregor

**Comment by NetanelBasal** [comment]
@dirkluijk thoughts?

**Comment by GregOnNet** [comment]
I missed to mention, that `test.each` works fine.
Only `it.each` causes problems.
