### ISSUE TITLE
angular 6?

### ISSUE THREAD

**Issue by PsychicCat** [NetanelBasal/spectator#14]
Any plans to support angular 6 soon (without needing rxjs-compat)?

**Comment by NetanelBasal** [comment]
Spectator doesn't depend on Rx. Did you encounter a problem with version 6?

**Comment by PsychicCat** [comment]
Hm, might just be that rxjs-lint failed to fix my imports in spec files. I will close this, must be a problem on my end. Thanks btw!

**Comment by bengry** [comment]
I agree that most of the community is going forward, but at least from my experience at work, we upgraded to Angular 6 and things are working fine as far as Spectator goes, I didn’t have to change a thing (using it with Jest, so YMMV).

However, if the rxjs is only used for a single type, I think that just requiring rxjs as a `peerDependency` with `^5.5` should be fine. No?

**Comment by bengry** [comment]
I agree that most of the community is going forward, but at least from my experience at work, we upgraded to Angular 6 and things are working fine as far as Spectator goes, I didn’t have to change a thing (using it with Jest, so YMMV).

However, if the rxjs is only used for a single type, I think that just requiring `rxjs` as a `peerDependency` with `^5.5` should be fine. No?

**Comment by NetanelBasal** [comment]
@bengry

I agree that most of the community is going forward, but at least from my experience at work, we upgraded to Angular 6 and things are working fine as far as Spectator goes, I didn’t have to change a thing (using it with Jest, so YMMV).

However, if the rxjs is only used for a single type, I think that just requiring rxjs as a `peerDependency` with `^5.5` should be fine. No?

**Comment by NetanelBasal** [comment]
No, because it used as a type, and the import path is different in version 6. But I really don't see it as a problem for time being to install rx-compact as dev dependency.

**Comment by bengry** [comment]
Again, agreed in theory, but in practice I think it increases the entry barrier to using Spectator, especially for new projects that have no other dependencies that need rxjs < 6.

In our case things work simply because we do have other package that require the rxjs-compat package, but as soon as those are gone it’s going to be harded to reason about why we’re keeping the compat library as a dependency (of any kind). But then again, by then hopefully most of the community that are on Angular 5 will transition to 6(+) and Spectator will move along with it.

**Comment by NetanelBasal** [comment]
I reopen the issue. Let's wait another month before we upgrade.

**Comment by PierreDuc** [comment]
Perhaps release the v6 support on the `next` branch on npm? Although it's not a big issue to have rxjs-compat as a dependency. There it's just used as a type inside spectator, it doesn't matter for tree shaking anyways

**Comment by NetanelBasal** [comment]
I opened the `next` branch and upgrade to Angular 6, but it seems that it still needs `rxjs-compat`.

**Comment by bengry** [comment]
@NetanelBasal I took a look at the code that uses rxjs in the library (`next` branch):
```typescript
// src/lib/src/internals.ts
  output<T, K extends keyof C = keyof C>(output: K): Observable<T> {
    const observable = this.component[output];
    if (observable instanceof Observable) {
      return observable as Observable<T>;
    } else {
      throw new Error(`${output} in not an @Output`);
    }
  }
```

the `Observable` type is not only used as a type as previously mentioned, but also at runtime (of the tests), with the `instanceof` keyword.

On another matter, what seems to need `rxjs-compat`? I didn't see anything that may need it.

**Comment by NetanelBasal** [comment]
You can see it yourself by pulling the `next` branch. It seems that the Observable type definition file is pointing to the compact package.
