### ISSUE TITLE
Sementic releases and changelogs

### ISSUE THREAD

**Issue by dirkluijk** [NetanelBasal/spectator#141]
As we already follow [Conventional Commits Specification](https://www.conventionalcommits.org/), I think it 's a good idea to maintain an automatic changelog.

We can maintain such changelog using [standard-version](https://github.com/conventional-changelog/standard-version) or [semantic-release](https://github.com/semantic-release).

**Comment by NetanelBasal** [comment]
standard-version

**Comment by dirkluijk** [comment]
👍 

I'll take a look this week when I have time.
