### ISSUE TITLE
Can't find a debug element for <selector>

### ISSUE THREAD

**Issue by fr0** [NetanelBasal/spectator#146]
Tests that passed in 3.10 are failing in 3.11.

```
expect(host.queryHost('.text')).not.toExist();
```

```
Error: Cannot find a debug element for .text
```

I'm not sure what to do with the error. `.text` is not supposed to exist (which is specifically what I'm checking for).

Simple to reproduce:

```javascript
@Component({
  selector: 'empty-comp',
  template: ``
})
class EmptyComponent {

}
describe('EmptyComponent', () => {
  let host: SpectatorWithHost<EmptyComponent>;
  const createHost = createHostComponentFactory({
    component: EmptyComponent,
    imports: [
      BrowserModule,
      FormsModule
    ]
  });
  it('should not have a text child', fakeAsync(() => {
    host = createHost(`<empty-comp></empty-comp>`);
    expect(host.queryHost('.text')).not.toExist();
  }));
});

```

**Comment by NetanelBasal** [comment]
@dirkluijk it probably related to the query changes. Can you check it, please?

**Comment by dirkluijk** [comment]
Yes, I think it is regression. I was already planning on expanding the test suites to cover some (edge) cases. Maybe even rewrite the whole test suite (before moving on to v4).

I’ll take a look at this issue first.

**Comment by NetanelBasal** [comment]
There are more issues regarding the new `types` changes. I will point them in the v4 pull request.

**Comment by fr0** [comment]
You will probably want to add a unit test to spectator for the `not.toExist()` case, since this something I do very often in my tests. (You could just copy my example above if you want.)

**Comment by dirkluijk** [comment]
Of course, thanks. I’ll sit behind my laptop later tonight.

**Comment by dirkluijk** [comment]
Released in 3.11.1.

**Comment by fr0** [comment]
npm still says 3.11.0 is the latest... do releases get automatically pushed?

**Comment by dirkluijk** [comment]
Sorry, I did something wrong. New collaborator in this repo.... just a sec.

**Comment by dirkluijk** [comment]
Done!
