### ISSUE TITLE
Not able to test if a Function has been called from constructor.

### ISSUE THREAD

**Issue by kafs1696** [NetanelBasal/spectator#15]
This is my code : 
**//app.component.ts**
`beforeEach(() => {
    spectator = createComponent({}, false);
    app = spectator.debugElement.componentInstance;
    translate = TestBed.get(TranslateService);
  });

  it('should create the app', async(() => {
    spyOn(spectator.component, 'setupLanguage').and.callThrough();
    spectator.fixture.detectChanges();
    app = spectator.debugElement.componentInstance;
    expect(app).toBeTruthy();
    expect(spectator.component.setupLanguage).toHaveBeenCalled();
  }));`

**//app.component.spec.ts**
`export class AppComponent {
  title = 'app';
  languageKeys = ['en', 'de', 'fr', 'it'];

  constructor(private translate: TranslateService) {
    this.setupLanguage();
  }
`

**//Here is the test output**
![screen shot 2018-05-16 at 12 47 29 pm](https://user-images.githubusercontent.com/9987781/40100871-5b85e03a-5907-11e8-9136-cd9df4d0fbee.png)

**Comment by NetanelBasal** [comment]
This is not related to spectator. You should spy on the method before creating the component. For example:
`spyOn(AppComponent.prototype, "method")`

**Comment by kafs1696** [comment]
Thank you @NetanelBasal. I followed your example and the test passed.
