### ISSUE TITLE
Testing directives

### ISSUE THREAD

**Issue by dirkluijk** [NetanelBasal/spectator#153]
I have been busy with unit testing today. I have the feeling that testing directives can be more elegant.

```ts
const createComponent = createHostComponentFactory({
  component: MyDirective,
  imports: [FormsModule]
});

it('should ...', () => {
  const spectator = createComponent('<input type="text" myDirective [(ngModel)]="externalValue" />');
  spectator.typeInElement('Foo', 'input');
});
```
This won't actually work: the `typeInElement` does a query inside the "component", not the host component. The "component" in this case is the directive. The workaround is: `spectator.typeInElement(text, spectator.element);`.

I have 2 suggestions:
1) change `SpectatorWithHost` to query from host for keyboard/event/input shortcuts (to do a wider search) 
2) or: make the selector for methods like `typeInElement()` optional and default to `spectator.element` 😄

(or we can do both)

**Comment by NetanelBasal** [comment]
I prefer not to introduce a breaking change. We can add the same support for the host, for example:

```ts
spectator.host.typeInElement(..);
spectator.host.click(..);
spectator.host.blur(..);
```

It can extend Spectator. What do you think?

**Comment by dirkluijk** [comment]
Yeah, that might be an improvement, however for this use case the change in https://github.com/NetanelBasal/spectator/pull/155 was already the solution (and that one is not breaking). 😉 

So I think that PR closes this issue.
