### ISSUE TITLE
Cannot test a component with nested service dependency

### ISSUE THREAD

**Issue by kafs1696** [NetanelBasal/spectator#16]
Following your Widget Example,
Lets Say I have a Test  **Component A** that depends on **Service B**, where **Service B** also depends on **Service C**. If i add the service B to Mocks, i still get the error saying "No provider for Service C". Isn't is supposed to mock the dependency tree? How can i solve this error?

**Test Error**
![screen shot 2018-05-24 at 12 51 59 pm](https://user-images.githubusercontent.com/9987781/40469129-505c2d72-5f51-11e8-9870-ca1314f13e09.png)

**Spec File**
![screen shot 2018-05-24 at 12 49 08 pm](https://user-images.githubusercontent.com/9987781/40468995-ed52783a-5f50-11e8-955d-0b1277966ad9.png)

**Component File**
![screen shot 2018-05-24 at 12 49 53 pm](https://user-images.githubusercontent.com/9987781/40469012-00bcfc6a-5f51-11e8-8186-809f2244f314.png)

**Core Service**
![screen shot 2018-05-24 at 12 34 41 pm](https://user-images.githubusercontent.com/9987781/40468477-5ce748a8-5f4f-11e8-9d7e-5bc7532cc812.png)

**Comment by NetanelBasal** [comment]
Yes, it should, can you reproduce it in [stackblitz](https://stackblitz.com/edit/spectator?file=app%2Fhello.component.spec.ts) so I can help you, please?

**Comment by kafs1696** [comment]
Sorry @NetanelBasal I was busy with other stuff and could not provide you the sample app. I will provide you in 1 to 2 days.

**Comment by NetanelBasal** [comment]
Closing this, as inactive.
