### ISSUE TITLE
Missing types for query() method

### ISSUE THREAD

**Issue by jpzwarte** [NetanelBasal/spectator#18]
According to internals.d.ts, the query method has the following types:
```
    /**
     *
     * @param {Type<T> | string} directiveOrSelector
     * @param {{read}} options
     * @returns {T}
     */
    query<R>(directiveOrSelector: string, options?: {
        read;
    }): Element;
    query<R>(directiveOrSelector: Type<any>, options?: {
        read;
    }): R;
```

That means that you have to cast the return value of the query method when passing a selector before you can use it. Can't we change the API so you can do: ```spectator.query<HTMLElement>('a').click()```?

**Comment by jpzwarte** [comment]
Isn't it simply just a question of changing ```Element``` to ```R``` here? https://github.com/NetanelBasal/spectator/blob/master/src/lib/src/internals.ts#L69

**Comment by NetanelBasal** [comment]
In general, you are right. It's a question of what is the more common case? If you most of the times query for DOM element it's more convenient. Don't you think so?

**Comment by jpzwarte** [comment]
Then perhaps change the return value to ```HTMLElement``` instead of ```Element``` so common things like ```.click()``` work without having to cast the return value?

**Comment by jpzwarte** [comment]
Because i didn't know that API existed 😁

**Comment by NetanelBasal** [comment]
It will click and trigger change detection for you.

**Comment by jpzwarte** [comment]
Excellent! Just changed my test to use that API :)

**Comment by NetanelBasal** [comment]
https://netbasal.gitbooks.io/spectator/api.html

**Comment by jpzwarte** [comment]
I guess we can close this issue then.

**Comment by NetanelBasal** [comment]
I love your idea, but it means that if I changed it, everyone would get the `any` type. It means that you must pass a type. 

`spectator.query<HTMLButtonElement>("button");`

**Comment by jpzwarte** [comment]
You could do ```query<R = Element>(directiveOrSelector: string, options?: { read }): R;```

**Comment by NetanelBasal** [comment]
lol, that's precisely what I did right now.

**Comment by NetanelBasal** [comment]
I'm releasing a new version with this change for all queries methods.

**Comment by jpzwarte** [comment]
Great, thanks!

**Comment by NetanelBasal** [comment]
Thank you. Feel free to give more feedback or issues. :)
