### ISSUE TITLE
Match jasmine-jquery for toHaveAttr matcher API 

### ISSUE THREAD

**Issue by jpzwarte** [NetanelBasal/spectator#21]
So jasmine-jquery defines toHaveAttr as: https://github.com/velesin/jasmine-jquery/blob/master/lib/jasmine-jquery.js#L466

For example: ```expect(spectator.query('span')).toHaveAttr('foo', 'bar');```

The current spectator matcher is a lot more verbose:
```expect(spectator.query('span')).toHaveAttr({ attr: 'foo', value: 'bar' });```

Can we change the API so it matches jasmine-jquery? 😄

**Comment by NetanelBasal** [comment]
Sure, I will check it, thanks.

**Comment by NetanelBasal** [comment]
Added two new `matchers` and deprecated the old ones not to introduce a breaking change.
`toHaveAttribue('foo', 'bar')`
`toHaveProperty('foo', 'bar')`
