### ISSUE TITLE
typeInElement and ngModel

### ISSUE THREAD

**Issue by dirkluijk** [NetanelBasal/spectator#22]
I have a component with a form. However, the `typeInElement()` function does not seem to work with the `ngModel` directive. I tried solving it with `fakeAsync` and `tick()` but the form control stays empty, and so does the model.

My component (simplified):
```typescript
@Component({
  selector: 'app-foo',
  template: '<form><input type="text" name="foo" class="foo" [(ngModel)]="model.foo" /></form>'
})
class FooComponent {
  model = {
    foo: ''
  };
}
```
My test code (simplified):
```typescript
describe('FooComponent', () => {
  const createComponent = createTestComponentFactory({
    component: FooComponent,
    imports: [FormsModule],
  });

  let spectator: Spectator<FooComponent>;

  it('should search when submitting form', fakeAsync(() => {
    spectator = createComponent();

    spectator.typeInElement('My value', '.foo');
    
    // tick(); // I tried this
    // spectator.detectChanges(); // ...and this
    
    expect(spectator.component.model.foo).toBe('My value'); // fails
  }));
});
```
Any help on this?

**Comment by NetanelBasal** [comment]
Can you reproduce [here](https://stackblitz.com/edit/spectator?file=app%2Fhello.component.spec.ts), so I can help you, please?

**Comment by dirkluijk** [comment]
Of course, here you go: https://stackblitz.com/edit/spectator-issue22-ngmodel

It seems change detection resets the value of the input element before the input event is being handled by the ngModel directive. But that's just a guess.

**Comment by NetanelBasal** [comment]
The problem is that ngModel is **async**. What you should do is:
```ts
describe('HelloComponent', () => {
  let host: SpectatorWithHost<HelloComponent>;

  const createHost = createHostComponentFactory({
    component: HelloComponent,
    imports: [FormsModule]
  });

  it('should search when submitting form', async(() => {
    host = createHost('<hello></hello>');

    host.hostFixture.whenStable().then(() => {
      host.typeInElement('My value', '.foo');
      expect(host.component.model.foo).toBe('My value');
    });
  }));
});

```

**Comment by NetanelBasal** [comment]
`model.foo` is winning because it executes after you run `typeInElement()`.

**Comment by dirkluijk** [comment]
Interesting! It did work. I also found an alternative "solution":

```typescript
// added async beforeEach
beforeEach(async(() => {
  host = createHost('<hello></hello>');
}));

it('should search when submitting form', () => {
  host.typeInElement('My value', '.foo');
  
  expect(host.component.model.foo).toBe('My value'); // fails
});
```

**Comment by NetanelBasal** [comment]
Yes, but it will work only on initialize.

**Comment by dirkluijk** [comment]
Good catch. Thanks for helping me out! Async testing can still be challenging sometimes.

**Comment by NetanelBasal** [comment]
Any time you need, I hope you are enjoying the library.

**Comment by dirkluijk** [comment]
Sure! It is how the default Angular test API should be... it makes Angular testing really fun again.

Keep up the good work.

**Comment by CodeCrusha** [comment]
host.hostFixture.whenStable().then(() => { ... }); let the test always pass with success, it does not matter which except you have in there (except(false).toBeTruthy() is true). I guess because its async. Just to point out, that the answer of NetanelBasal is not correct.

**Comment by NetanelBasal** [comment]
@CodeCrusha can you reproduce what you're saying?

**Comment by elena-dev-thought** [comment]
This is so strange for me it work when I put the whenStable outside of the form interactions.
`host.typeInElement(
      formPlace.wifiSpeed,
      '[formControlName="workplaceWifiSpeed"]'
    );
    host.click('[formControlName="workplacePowerPlug"]')
    host.hostFixture.whenStable().then(() => {
      expect(store.selectSnapshot(AddWorkplaceState.formDirtyValue)).toBe(true);
      host.click('.submit');
      host.detectChanges();
      expect(store.selectSnapshot(AddWorkplaceState.formDirtyValue)).toBeFalsy()
    });`

and this will not work: 
`host.hostFixture.whenStable().then(() => {
 host.typeInElement(
      formPlace.wifiSpeed,
      '[formControlName="workplaceWifiSpeed"]'
    );
    host.click('[formControlName="workplacePowerPlug"]')
      expect(store.selectSnapshot(AddWorkplaceState.formDirtyValue)).toBe(true);
      host.click('.submit');
      host.detectChanges();
      expect(store.selectSnapshot(AddWorkplaceState.formDirtyValue)).toBeFalsy()
    });`

**Comment by dirkluijk** [comment]
Yes, you first have to wait for the `fixture.whenStable()` promise before typing in the form.

As a side note: you can use async/await to make it more elegant. E.g:
```typescript
it('should check and uncheck', async () => {
    host = createHost('<my-checkbox [(ngModel)]="checked"></my-checkbox>');
    await host.hostFixture.whenStable();

    host.click('.eb-control');

    expect(host.element).toHaveClass('checked');
});
```

**Comment by orosro** [comment]
Hello,

I know this is old, but following the above did not solve the problem, or better said,  the tests are randomly failing or passing

```@NgModule({
	imports: [MatDatepickerModule, MatMomentDateModule],
	providers: [
		{ provide: MAT_DATE_FORMATS, useValue: NK_DATE_DEFAULT_FORMATS },
		{
			provide: DateAdapter,
			useClass: MomentDateAdapter,
			deps: [MAT_DATE_LOCALE],
		},
	],
})
export class MainModule {}

fdescribe('NkDateTimeEdit component', () => {
	const createHost = createHostFactory({
		component: NkDateTimeEdit,
		imports: [
			MainModule,
			NkDateTimeEditModule,
			FormsModule,
			ReactiveFormsModule,
		],
		declareComponent: false,
		detectChanges: false,
		providers: [
			{ provide: MAT_DATE_FORMATS, useValue: NK_DATE_DEFAULT_FORMATS },
			{ provide: DateTimeAdapter, useClass: NkMomentDateTimeAdapter },
		],
	});

	let host;

	afterEach(() => {
		if (host) {
			host.hostFixture.destroy();
			host.fixture.destroy();
			host = null;
		}
	});

it('should update value when inputs change ', fakeAsync(async () => {
		host = createHost(
			'<nk-datetime-edit showSeconds [(value)]="rawValue"></nk-datetime-edit>'
		);

		host.hostComponent.rawValue = moment.utc([2017, 5, 6, 1, 2, 3, 4]);
		host.detectChanges();
		await host.fixture.whenStable(); // it doesn't matter which one I use
		await host.hostFixture.whenStable();

		const hourControlInput = host.query('[formcontrolname="hh"]');
		host.typeInElement(7, hourControlInput);
		hourControlInput.blur();

		const minuteControlInput = host.query('[formcontrolname="mm"]');
		host.typeInElement(8, minuteControlInput);
		minuteControlInput.blur();

		const secondsControlInput = host.query('[formcontrolname="ss"]');
		host.typeInElement(9, secondsControlInput);
		minuteControlInput.blur();

		host.queryAll('.mat-calendar-body-cell')[10].click();

		host.detectChanges();

		expect(host.hostComponent.rawValue.toString()).toEqual(
			moment([2017, 5, 11, 7, 8, 9, 4]).toString()
		);
	}));

})
```


I'm using 
spectator v6.0.0,
jasmine: 3.6.2
karma: 5.0.0
