### ISSUE TITLE
Error when using multiple factories

### ISSUE THREAD

**Issue by dirkluijk** [NetanelBasal/spectator#23]
Just wanted to report that in some situations this error can appear:

```
Illegal state: Could not load the summary for directive HostComponent.
```

This happens when you use multiple factories (e.g. `createTestComponentFactory` and `createHostComponentFactory`) in the same test ("describe") block.

Is this intended? Maybe a better error message should be visible.

**Comment by NetanelBasal** [comment]
Hey, thanks for the report. It's a limitation of `TestBed.` You can create one `createTestComponentFactory` per describe.

**Comment by NetanelBasal** [comment]
If you have further questions, let me know.
