### ISSUE TITLE
Testing HTTP interceptors

### ISSUE THREAD

**Issue by dirkluijk** [NetanelBasal/spectator#25]
Hi,

I just wanted to share this Gist: [testing HTTP interceptors with Spectator](https://gist.github.com/dirkluijk/3a29f5abc7e57d7e6e3b5788f462625c).
Maybe it's nice to have a special `HttpInterceptorFactory` on the roadmap of Spectator. 😎

**Comment by NetanelBasal** [comment]
Looks great! thanks.

**Comment by NetanelBasal** [comment]
Added to the official examples. https://netbasal.gitbook.io/spectator/examples/http-interceptors

**Comment by kiyonlin** [comment]
The [link](https://netbasal.gitbook.io/spectator/examples/http-interceptors) above is broken. Could you consider putting the examples in the readme file? @NetanelBasal

**Comment by rafaelss95** [comment]
@NetanelBasal Could you put the new link here or in README?

**Comment by NetanelBasal** [comment]
https://gist.github.com/dirkluijk/3a29f5abc7e57d7e6e3b5788f462625c
