### ISSUE TITLE
Testing Components with service in OnInit

### ISSUE THREAD

**Issue by FrankMerema** [NetanelBasal/spectator#27]
Hi,

While is was testing with your beautiful library I ran into a exception at the `mocks` part.
In most of my components I subscribe to an observable, for example ``` this.route.paramMap.subscribe(paramMap => {}); ``` and it will crash with `TypeError: Cannot read property 'subscribe' of null`.

So I have created a [Gist](https://gist.github.com/FrankMerema/8c84be6026df1ecf73fdc503fef331ed) with minimal setup code as example for other people.

Maybe it's nice to make a way to configure the return value of the mocked functions. I saw the default return value was 'null' but with observables it would be nice to have some way to configure it.

Example (brain dump):

```
@Component({})
class MyComponent {
    constructor(private barService: BarService,
                private route: ActivatedRoute) {}

    ngOnInit(): void {
        // this fails without configuring the mocks:

        // ERROR: Cannot read property 'subscribe' of null
        this.route.paramMap.pipe(
                switchMap(() => this.barService.getFoo())
            ).subscribe(); 

        // and this fails too...
        this.barService.getBar();
    }
}

describe('', () => {
    // proposal, a way to configure mocks in the factory?
    // or just mock all Observables on the mock prototypes by default...

    const createComponent = createTestComponentFactory({
        component: MyComponent,
        mocks: [[BarService, { getFoo: of('lorem'), getBar: 'ipsum' }]]
    });


    it('', () => {
        const spectator = createComponent();

        // detectChanges should work without issues
    });
})
```

**Comment by NetanelBasal** [comment]
Closing this issue. If you have any further questions, let me know.
