### ISSUE TITLE
Library node_modules is checked into git

### ISSUE THREAD

**Issue by benelliott** [NetanelBasal/spectator#28]
I am working on a new feature that I would like to eventually submit as a pull request, but that feature makes some changes to the library's dependencies and I was surprised to find that the dependencies are checked into git. Is this necessary? For one, it makes it hard to see the real changes a pull request is making as they are buried in the noise of minor dependency updates.

**Comment by NetanelBasal** [comment]
Hey, this is a bug, it should not be there.

**Comment by NetanelBasal** [comment]
It should be in gitignore. If your feature involved breaking changes, let me know, so we can release it with the next major version where we upgrade to Angular 6.

**Comment by benelliott** [comment]
Oh cool thanks, I was worried it was part of your workflow. I've just submitted #29 to fix it (.gitignore just needed to be reapplied). I don't think the other PR will have breaking changes.

**Comment by NetanelBasal** [comment]
Thanks

**Comment by benelliott** [comment]
Have you considered packaging the library with the CLI?

**Comment by NetanelBasal** [comment]
They added this option only in v6. I'll do it in the future when I find the time.

**Comment by benelliott** [comment]
If you would like a PR for it I might be able to give it a go.

**Comment by NetanelBasal** [comment]
Go for it. 👍
