### ISSUE TITLE
Add option to defer initial host change detection

### ISSUE THREAD

**Issue by euangoddard** [NetanelBasal/spectator#3]
I've been trying to test a directive with `EasyTestWithHost` and it's fantastic for all my cases save one -- I have one test case where I need to set-up a spy which I know should get triggered in the initial change detection cycle (in `ngAfterContentInit` in my case).

If I do `TestBed.get(token)` before I called `this.create()` (in order to spy on a method), I get an error saying `overrideComponent` cannot be called after `inject` which makes sense. Ideally I'd like to have an option for `this.create()` which suppresses the first change detection in the host so that I can call it once I've created my spy.

Looking at the code, this may not be a trivial change as the change detection may be needed for other aspects of the test set-up. I'll have a play if I get time and submit a PR.

**Comment by NetanelBasal** [comment]
Thanks, this is a great idea. I am quite busy right now, but I would love to see a PR.

**Comment by NetanelBasal** [comment]
I think you can add a little example, so others ( or me ) will try to add this too.

**Comment by euangoddard** [comment]
Let me see if I can chop down my code to a simple use-case to give a concrete example

**Comment by euangoddard** [comment]
Here's an example of the problem: https://gist.github.com/euangoddard/d5f63ab13153fac5e99789b406293e6a

This use-case is a lot more simplistic than I have and in the example given I could override the provider when I set up the testing module. That option isn't available to me in the real case

**Comment by NetanelBasal** [comment]
This is the line where change detection is triggered:
https://github.com/NetanelBasal/ngx-easy-test/blob/master/src/easy-test.ts#L165
Try remove it temporarily and see if it's working.

**Comment by NetanelBasal** [comment]
We have new API with support for your request. Check it.

**Comment by euangoddard** [comment]
That looks perfect. I'll try it out when I get a chance. Many thanks for this!
