### ISSUE TITLE
SpectatorWithHost resetting inputs when detectChanges is set to true

### ISSUE THREAD

**Issue by bengry** [NetanelBasal/spectator#31]
Given the following component:
```typescript
@Component({
	selector: 'my-component',
    template: `
      <div>
        <ng-container [ngTemplateOutlet]="content"></ng-content>
      </div>`,
	changeDetection: ChangeDetectionStrategy.OnPush,
	encapsulation: ViewEncapsulation.None,
})
export class MyComponent {
  @Input() someInput: boolean;
  @Input() content: TemplateRef;
}
```

And the following test code:
```typescript
let spectator: SpectatorWithHost<MyComponent>;
const createHost = createHostComponentFactory({
  component: MyComponent,
  shallow: true
});

it('input test', () => {
  spectator = createHost(`
    <ng-template #content>
      <span>Sample content</span>
    </ng-template>

    <my-component
        [someInput]="someInput"
        [content]="content">
    </my-component>
`, true, { someInput: true })

  expect(spectator.component.someInput).toBe(true);
});
```

The test `'input test'` fails, and `someInput` is `undefined`.

passing `false` as the `detectChanges` parameter (to `createHost`) results in `someInput` being `true`, but as soon as you run a changeDetection (via `spectator.detectChanges()` to check the DOM, the values reset.

**Comment by NetanelBasal** [comment]
I'm not sure it's a problem. As you can see here, it should work. 
https://github.com/NetanelBasal/spectator/blob/master/src/lib/src/host.ts#L103

Can you create a demo so that I can investigate more, please?
https://stackblitz.com/edit/spectator?file=app%2Fhello.component.spec.ts

**Comment by bengry** [comment]
@NetanelBasal I debugged this a bit, and it seems like [this line](https://github.com/NetanelBasal/spectator/blob/2856a80c867657e5d6a8c520e08876d20ccc7737/src/lib/src/host.ts#L107) is causing the issue (i.e. the inputs are set fine before it).

You can find a repro for the complexInputs issue, forked from the StackBlitz you linked here: https://stackblitz.com/edit/spectator-9gg3yx

**Comment by NetanelBasal** [comment]
can you move this line to 101 and check, please?

**Comment by bengry** [comment]
@NetanelBasal Move what line to 101?

**Comment by NetanelBasal** [comment]
spectatorWithHost.hostFixture.detectChanges();

**Comment by NetanelBasal** [comment]
```ts
    if(detectChanges) {
      spectatorWithHost.hostFixture.detectChanges();
    }
    
    if (initialInputs) {
      spectatorWithHost.setInput(initialInputs);
    }

    if (detectChanges) {
      /** Detect changes on the component - useful for onPushComponents */
      spectatorWithHost.detectComponentChanges();
    }

```

**Comment by bengry** [comment]
@NetanelBasal Seems like that works, but I'm not sure how you can run changeDetection before you set the inputs - after all, you want the detection to run on the component **with** the changes.

**Comment by NetanelBasal** [comment]
Yes, but the actual component is:
`spectatorWithHost.detectComponentChanges();`

You moved the line of the **host**.

**Comment by bengry** [comment]
@NetanelBasal I actually just checked this again against a real component I have and it seems like there's still some issue in this regard. I'll try and make a more exact repro on StackBlitz and add it when done.

**Comment by NetanelBasal** [comment]
Already publish 1.8.1 with the fix. Let me know.

**Comment by bengry** [comment]
@NetanelBasal FYI there's already a v1.11. Why not 1.11.1?

**Comment by NetanelBasal** [comment]
I am using an automatic tool, and it was doing some crazy things.

**Comment by NetanelBasal** [comment]
we will be aligned in v2.0

**Comment by bengry** [comment]
So 1.8.1 includes everything that 1.11 includes? At any rate, I suggest publishing a 1.11.1 (even if it's === 1.8.1), since no one will see the new fix otherwise (until the next version), and if you install 1.8.1, upgrading to an actual "lower" version is easily possible.

**Comment by NetanelBasal** [comment]
Let me check.

**Comment by NetanelBasal** [comment]
I need to revert the whole thing; there was a mistake.

**Comment by bengry** [comment]
You can't unpublish a package on npm, just deprecate it.

Please post an update when a new version's published, I'll update our projects.

**Comment by NetanelBasal** [comment]
Why are you not upgrading to 1.11?

**Comment by bengry** [comment]
I upgraded to 1.11 originally, but it had the bug I faced that caused 1.8.1 to be released.
That's why I wanted 1.11.1 :-).

I'll give it a try tomorrow. Thanks for the hard work!

**Comment by NetanelBasal** [comment]
Thank you.

**Comment by NetanelBasal** [comment]
This change broke some of our tests.
