### ISSUE TITLE
Dedicated page in docs about life cycle hooks

### ISSUE THREAD

**Issue by dirkluijk** [NetanelBasal/spectator#38]
Hi, 

Some of my co-workers had trouble with life cycle hooks. This may be obvious for experienced Angular devs, but maybe it would be nice to have a dedicated page in the docs `Components -> Lifecycle hooks`:

> ## Lifecycle hooks
> When using regular `Spectator` (with `createTestComponentFactory`), lifecycle hooks on the tested component are not triggered. You have trigger them yourself, e.g. by calling `spectator.component.ngOnChanges()`. This is because live cycle hooks only get triggered when input bindings are updated by a parent view.
>
> To profit from automatic life cycle hooks, you will need the `SpectatorWithHost`.
>
> ```ts
> host = createHost(`<hello title="Hello"></hello>`);
> ```
>
> Please note that, for complex input bindings, `createHost('<my-component></my-component>', true, { someInput: 'value' })` will not work, because the third argument will only update the component instance and not trigger life cycle hooks. Instead, use a custom host:
> ```ts
> @Component({selector: 'host'})
> class HostComponent {
>   myTitle = 'World';
> }
>
> describe('HelloComponent', () => {
>   let host: SpectatorWithHost<HelloComponent, HostComponent>;
>
>   const createHost = createHostComponentFactory({
>     component: HelloComponent,
>     host: HostComponent
>   });
>
>   it('does trigger lifecycle hooks when using a host ', () => {
>     host = createHost(`<hello [title]="myTitle"></hello>`);
>   });
> });
> ```

I hope this can be of any value for the docs ;)

**Comment by NetanelBasal** [comment]
>  lifecycle hooks on the tested component are not triggered

I'm not sure what you mean. Lifecycle hooks are called, for example, ngOnInit.

**Comment by dirkluijk** [comment]
Hm, I see. My mistake. But for ngOnChanges, this _is_ actually different somehow:
https://stackblitz.com/edit/spectator-sw9rk2

Can you explain this difference?

**Comment by NetanelBasal** [comment]
`ngOnChanges` isn't called when inputs are set programmatically. In the host case, it's not considered programmatically.

**Comment by dirkluijk** [comment]
Ah. Just found [this article](https://medium.com/@christophkrautz/testing-ngonchanges-in-angular-components-bbb3b4650ee8). So the above explanation is correct but only for ngOnChanges.

Thanks for looking into it.
