### ISSUE TITLE
Option to use Jest for Spectator mocking

### ISSUE THREAD

**Issue by dirkluijk** [NetanelBasal/spectator#39]
We successfully migrated from Karma/Jasmine to Jest (with Spectator unit tests).

Spectator uses Jasmine for the mocking implementation, this still works fine. However, as Jest has its own mocking API, is it possible to make Spectator use Jest for mocks? This prevents mixing two different API's for mocking.

e.g.
```ts
const createComponent = createTestComponentFactory({
  component: MyComponent,
  mocks: [MyService]
});

let spectator: Spectator<MyComponent>;

beforeEach(() => {
  spectator = createComponent();

  // spectator.get(MyService).someMethod.andReturn('foo'); // with Jasmine
  spectator.get(MyService).someMethod.mockReturnValue('foo'); // with Jest
});
```

Maybe by checking if Jest is available and automatically use Jest instead of Karma, or by configuring Spectator somehow?

I am willing to contribute for this feature request.

**Comment by NetanelBasal** [comment]
It can be nice. Currently, I don't have the time, but feel free to do it.

**Comment by dirkluijk** [comment]
Initial attempt: https://github.com/NetanelBasal/spectator/pull/40.

**Comment by LayZeeDK** [comment]
You would have to create a sub-package specific to Jest.

**For Jest**
```typescript
import { createTestComponentFactory } from '@netbasal/spectator/jest';

const createComponent = createTestComponentFactory({
  component: MyComponent,
  mocks: [MyService]
});

let spectator: Spectator<MyComponent>;

beforeEach(() => {
  spectator = createComponent();

  spectator.get(MyService).someMethod.mockReturnValue('foo'); // with Jest
});
```

**For Jest**
```typescript
import { createTestComponentFactory } from '@netbasal/spectator';

const createComponent = createTestComponentFactory({
  component: MyComponent,
  mocks: [MyService]
});

let spectator: Spectator<MyComponent>;

beforeEach(() => {
  spectator = createComponent();

  spectator.get(MyService).someMethod.andReturn('foo'); // with Jasmine
});
```

Similarily a `createService` which can be Jest-specific by importing like this:
```typescript
import { createService} from '@netbasal/spectator/kest';
```

This is a similar problem to what `rxjs-marbles` needed to implement `fakeSchedulers` for multiple testing frameworks:
https://blog.angularindepth.com/rxjs-testing-with-fake-time-94114271eed2

**Comment by dirkluijk** [comment]
That sounds like a good idea!

@NetanelBasal if you agree, i’ll update the PR.

**Comment by NetanelBasal** [comment]
👌🏻

**Comment by dirkluijk** [comment]
Will take a look at it. We have switched to Jest for our Angular project so I have a good project to test against.
