### ISSUE TITLE
v1.13.1 not released

### ISSUE THREAD

**Issue by jeekapascual** [NetanelBasal/spectator#41]
Hi, unfortunately v1.13.1 isn't available on npm: https://www.npmjs.com/package/@netbasal/spectator

I will be needing the patch which supports content projection in mocked components. It exists in the aforementioned release.

As we are still using angular 5, I cannot use the next available version which contains this patch (v2.0.2). Will it be possible to republish v1.13.1? Thanks! We are currently using v1.13.0.

For the meantime, our workaround is to explicitly set the template option in MockComponent to `<ng-content></ng-content>`

**Comment by NetanelBasal** [comment]
You have problems using it with Angular 5, or you are just assuming?

**Comment by jeekapascual** [comment]
When I am mocking components via the `MockComponent` function, I am required to pass in the template. For example:

parent.component.html
```
<card>
  <heading>
    <div>{{ header }}</div>
  </heading>
  <body></body>
</card>
```

card.component.html
```
<ng-content></ng-content>
etc..
...
```

Instead of being able to do this:
```
createHostComponentFactory({
  declarations: [
    MockComponent({ selector: 'card' }),
    MockComponent({ selector: 'body' }),
    MockComponent({ selector: 'heading' })
  ]
});
```

I have to pass in template in order for `<custom>` to be taken into account:
```
createHostComponentFactory({
  declarations: [
    MockComponent({ selector: 'card', template: '<ng-content></ng-content>' }),
    MockComponent({ selector: 'body', template: '<ng-content></ng-content>'  }),
    MockComponent({ selector: 'heading', template: '<ng-content></ng-content>'  })
  ]
});
```
If I am working with multiple nested components, I have to explicitly state the template for each. This fix where a default template is set by `createHostComponentFactory` is available in v1.13.1.

**Comment by NetanelBasal** [comment]
I think you can use the newer version even with Angular 5, can you try it, please?

**Comment by jeekapascual** [comment]
Sorry for the delay in responding.

I've tested `v2` of spectator and it does work, however it explicitly requiring `angular@6` makes it difficult on my side. I'm working on a library that it set to use `angular@5` (won't be able to upgrade soon).

`v1.13.1` is the latest tag I could work with `angular@5`.

**Comment by NetanelBasal** [comment]
It's only a **peer dependency**; you can use it with Angular 5 with no problem,

**Comment by jpascual-pm** [comment]
Hello, sorry for the delay in responding. I saw you've closed this issue, but I still want to comment to confirm that it works on `angular@5`. As you said, it is after all a peerDependency.
