### ISSUE TITLE
Support host component from another module

### ISSUE THREAD

**Issue by fr0** [NetanelBasal/spectator#42]
Error I'm getting:

```
	Error: Type EditorTestHostComponent is part of the declarations of 2 modules: AtlasDevToolsModule and DynamicTestModule! Please consider moving EditorTestHostComponent to a higher module that imports AtlasDevToolsModule and DynamicTestModule. You can also create a new NgModule that exports and includes EditorTestHostComponent then import that NgModule in AtlasDevToolsModule and DynamicTestModule.
```

Is it possible to support my `host` component coming from another module?

**Comment by NetanelBasal** [comment]
Can you add the full code, please? I can't help you with only this.

**Comment by fr0** [comment]
Short version:

```
  let host: SpectatorWithHost<HelloWorldComponent,EditorTestHostComponent>;
  const createHost = createHostComponentFactory({
    component: HelloWorldComponent,
    imports: [AtlasDevToolsModule, RouterModule.forRoot([])],
    providers: [{provide: APP_BASE_HREF, useValue: '/'}],
    host: EditorTestHostComponent
  });
  it('works', () => {
    const host = createHost(view);
  });
```

I can't post the full code because it's not open source, but the key part is that `EditorTestHostComponent` is part of `AtlasDevToolsModule`, which seems to be the issue that Angular is complaining about.

I don't know what the right workaround/solution is, because it seems like your code is assuming that if there's a host component, that host component isn't part of any other module and needs to be included in the dynamic host module's `declarations`:.

https://github.com/NetanelBasal/spectator/blob/master/src/lib/src/config.ts#L60

**Comment by NetanelBasal** [comment]
You can create a new component that extends this one.

**Comment by fr0** [comment]
That is a reasonable workaround. Thanks for the help!

**Comment by NetanelBasal** [comment]
You're welcome.
