### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by fr0** [NetanelBasal/spectator#45]
Installing the latest version of spectator (`2.0.3`) in a project with Angular 7.0.0 gives the following warnings:

```
warning " > @netbasal/spectator@2.0.3" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > @netbasal/spectator@2.0.3" has incorrect peer dependency "@angular/core@^6.0.0".
```

Since Angular 7 was officially released on 2018-10-18, it would be nice if spectator supported it.

**Comment by NetanelBasal** [comment]
I believe it should work with v7, it's just a warning, but I need to test it.

**Comment by benelliott** [comment]
It does indeed work with v7, those warnings can be ignored for now.

**Comment by benelliott** [comment]
The peer dependencies have been updated to ^7.0.0 as of v2.1.0.
