### ISSUE TITLE
Complex Input properties

### ISSUE THREAD

**Issue by fr0** [NetanelBasal/spectator#5]
Great library! Looking forward to trying it out.

In your example, you have:

```
  host = createHost(`<zippy title="Zippy title"></zippy>`);
```

I was curious to know if you've thought of a way to pass complex objects as input parameters instead of just simple primitives. I occasionally create components that require this, usually receiving those objects from another component.

For example, It could be useful to be able to do something like this:

```
  host = createHost(`<zippy title="Zippy title" [options]="options"></zippy>`, { options: ... });
```

Thanks!

**Comment by NetanelBasal** [comment]
You can do this:
```ts
host = createHost(`<zippy title="Zippy title" [options]="{color: 'blue'}"></zippy>`);
expect(host.query(".color")).toHaveText("blue");
```

Or you need something more than that?

**Comment by NetanelBasal** [comment]
The second way is to use custom host component:

```ts
@Component({ selector: "custom-host", template: "" })
class CustomHostComponent {
  title = "Custom HostComponent";
  options = {color: 'blue'};
}

describe("With Custom Host Component", function() {
  let host: SpectatorWithHost<ZippyComponent, CustomHostComponent>;

  const createHost = createHostComponentFactory({
    component: ZippyComponent,
    host: CustomHostComponent
  });

  it("should..", () => {
    host = createHost(`<zippy [title]="title" [options]="options"></zippy>`);

    expect(host.query(".color")).toHaveText("blue");
  });
});

```

**Comment by NetanelBasal** [comment]
Done. Now you can also write it like that: 
```ts
  it("should support complex objects", () => {
    const options = { color: "blue" };
    host = createHost(`<zippy title="Zippy title"></zippy>`, true, { options });

    expect(host.query(".color")).toHaveText("blue");
  });
```

**Comment by fr0** [comment]
Thanks! That definitely solves my problem.

**Comment by NetanelBasal** [comment]
Already added. https://netbasal.gitbooks.io/spectator/components/testing-component-with-host.html

**Comment by splincode** [comment]
@NetanelBasal Oh, Thank you))

**Comment by akcasoy** [comment]
> Done. Now you can also write it like that:
> 
> ```ts
>   it("should support complex objects", () => {
>     const options = { color: "blue" };
>     host = createHost(`<zippy title="Zippy title"></zippy>`, true, { options });
> 
>     expect(host.query(".color")).toHaveText("blue");
>   });
> ```

should this still work with the Version 4.11.1? I can just give 1 or 2 arguments in createHost function.

Also [on this page](https://github.com/ngneat/spectator#user-content-testing-with-host),  this is done in a different way.
