### ISSUE TITLE
Add schematics support

### ISSUE THREAD

**Issue by NetanelBasal** [NetanelBasal/spectator#53]
1. Create `ng add @netbasal/spectator` command. 
2. Change the basic spec file that the CLI generates to Spectator template.

**Comment by dirkluijk** [comment]
Nice idea. But what should a spec file look like? Or can you provide different spec templates for pipes/services/components/etc?

**Comment by NetanelBasal** [comment]
Yes. `ng g c --spec` or `ng g c --spec withHost`

**Comment by dirkluijk** [comment]
Nice. "Accepts PR" -> no experience with creating schematics, but maybe I have time left this week.

**Comment by NetanelBasal** [comment]
lol, it will be awesome, you can start with the `ng add` command, it's easy.  https://nitayneeman.com/posts/making-an-addable-angular-package-using-schematics/

**Comment by NetanelBasal** [comment]
Released in v3.3.0

**Comment by rexebin** [comment]
Hi @NetanelBasal would you tell me how can I generate spectator template with the cli please? `ng g c --spec` only generate default angular cli spec in my project.

**Comment by NetanelBasal** [comment]
You need to install spectator cli. It does not work with angular-cli. https://github.com/NetanelBasal/spectator-cli

**Comment by dirkluijk** [comment]
Whoa. Didn't know that yet. AWESOME.

**Comment by rexebin** [comment]
@NetanelBasal Thank you. Awesome lib you have created.

**Comment by rexebin** [comment]
@NetanelBasal there might be a way to create a set of schematics extending the angular-cli and override the spec templates with spectator spec templates, works like @nrwl/schematics or @ngrx/schematics etc.

**Comment by NetanelBasal** [comment]
Yes, I'm sure there is a way. Unfortunately, I do not have time at the moment to work on it. If you want to create a PR, go ahead 👍.

**Comment by rexebin** [comment]
In my project (nx workspace), I have created a simple component schematic extending `@schematics/angular`'s component schematic, replacing the spec (run the default cli component schematics without generating spec, then copy a spectator spec template into the folder). Not sure how would this work in spectator lib. I will see what I can do.

**Comment by NetanelBasal** [comment]
It should be the same, thanks!
