### ISSUE TITLE
IE not working

### ISSUE THREAD

**Issue by NetanelBasal** [NetanelBasal/spectator#54]
@benelliott your application tests are working in IE? IE stopped working when we upgrade to 2+. 2- is working.

 cc @dirkluijk

**Comment by benelliott** [comment]
Hi, do you mean that unit tests written using Spectator won't run on IE?

I haven't tried it personally but can give it a try.

IE11?

**Comment by benelliott** [comment]
Just had a quick look - seems like it might be because dom-testing-library is distributed in ES6.

**Comment by NetanelBasal** [comment]
Makes sense. How can we fix it?

**Comment by benelliott** [comment]
I'm not sure 🤔 	

Just spent a few minutes playing with `tsconfig` (`allowJs`, `importHelpers`) but I didn't get anywhere. According to this SO link you can't do it with just TypeScript:

https://stackoverflow.com/questions/50090972/typescript-transpile-es6-js-dependency-to-es5

I guess one option would be to fork `dom-testing-library`, distribute it as ES5 and depend on that instead (then maybe send a PR to the original repo).

**Comment by NetanelBasal** [comment]
I downgraded our application to the version with the `dom-testing-library`, and it works. We need to find a solution; we support IE11.

**Comment by benelliott** [comment]
Do you mean to the version _without_ dom-testing-library?

**Comment by NetanelBasal** [comment]
sorry, yes.

**Comment by benelliott** [comment]
Ok yeah I am pretty certain the issue is with the `dom-testing-library` build pipeline. It's a pretty wacky custom solution but doesn't really seem to be doing what it is supposed to AFAICT.

**Comment by NetanelBasal** [comment]
Do we need to open an issue in the repo?

**Comment by benelliott** [comment]
Yeah, I think so - just investigating it myself atm as for some reason `react-testing-library` is compiled with Babel polyfills included but `dom-testing-library` isn't, and they have very similar configurations.

**Comment by benelliott** [comment]
Actually... due to a few red herrings, I might have missed an obvious solution - updating to the latest version of `dom-testing-library` might work. Are you able to test it?

**Comment by NetanelBasal** [comment]
I will on Sunday.

**Comment by benelliott** [comment]
Nope... it's a bit better but still has some arrow functions. I will have to ask the library author to release an ES5 version.

**Comment by benelliott** [comment]
I've opened https://github.com/kentcdodds/dom-testing-library/issues/160

**Comment by NetanelBasal** [comment]
Thanks!

**Comment by NetanelBasal** [comment]
Need to bump dom-testing-library version.

**Comment by NetanelBasal** [comment]
fixed in 3.0.0

**Comment by benelliott** [comment]
@NetanelBasal 	Thanks!
