### ISSUE TITLE
Imports in createService method doesn't work

### ISSUE THREAD

**Issue by slawojstanislawski** [NetanelBasal/spectator#55]
This is an example tested service, which uses Angular's FormBuilder:

```
import {Injectable} from '@angular/core';
import {FormBuilder} from '@angular/forms';

@Injectable()
export class FormsService {
  constructor(
    private fb: FormBuilder,
  ) {}
}
```

Here's the test case for it, using the 'imports' property
```
import {ReactiveFormsModule} from "@angular/forms";
import {createService} from "@netbasal/spectator";
import {FormsService} from "./media.service";

describe('FormsService', () => {
  const spectator = createService<FormsService>({
    imports: [
      ReactiveFormsModule
    ],
    service: FormsService,
  });

  it('should create', () => {
    expect(spectator.service).toBeTruthy();
  });
});
```

What I get in an error - it doesn't find the FormBuilder:
`Error: StaticInjectorError(DynamicTestModule)[FormsService -> FormBuilder]: 
  StaticInjectorError(Platform: core)[FormsService -> FormBuilder]: 
    NullInjectorError: No provider for FormBuilder!`

**Comment by NetanelBasal** [comment]
Can you reproduce it on stackblitz, please?

**Comment by NetanelBasal** [comment]
Works on the latest RC version. 
https://stackblitz.com/edit/angular-testing-spectator-neorxf

**Comment by slawojstanislawski** [comment]
Sorry, didn't have time recently to create a reproduction. Will verify soon, thank you for investigating.

**Comment by slawojstanislawski** [comment]
Works ok.
