### ISSUE TITLE
[feat] mockProvider for properties

### ISSUE THREAD

**Issue by MartinNuc** [NetanelBasal/spectator#56]
Imagine testing a service depending on observable from another service:

```
@Injectable({
  providedIn: 'root'
})
export class ConsumerService {
   constructor(private serviceWithObservable: ServiceWithObservable) {
      serviceWithObservable.obs$.subscribe(...)
   }
}

@Injectable({
  providedIn: 'root'
})
export class ServiceWithObservable {
   obs$ = new Subject();
}
```

For testing services we use `mocks` array which calls `mockProvider` which works great but it creates spies only for methods. Observable property is missing so in the test you need to do something like:

```
const serviceWithObservable = TestBed.get(ServiceWithObservable) as ServiceWithObservable;
serviceWithObservable.obs$ = new Subject();
```

**- What do you think about adding parameter for properties to `mockProvider`?**

Eg:

```
providers: [
   mockProvider(ServiceWithObservable, {
      obs$: new Subject()
   })
]
```

Could be used with `Object.assign` or something to add these properties to the mock.

**Comment by MartinNuc** [comment]
I've just noticed interesting thing - until I reference the service in my test (eg calling function, reading property) the constructor is not executed. I thought constructor is executed when creating a test module.

**Comment by benelliott** [comment]
You can't - see https://github.com/jasmine/jasmine/issues/1442

But I think the request is to just add a shorthand to extend spy objects with non-spy properties.

**Comment by MartinNuc** [comment]
Exactly as @benelliott says. I would like to add properties when creating a mock.

**Comment by NetanelBasal** [comment]
Could you create a PR without breaking changes?

**Comment by MartinNuc** [comment]
@NetanelBasal Yes I can if you agree with this proposal:

```
providers: [
   mockProvider(ServiceWithObservable, {
      obs$: new Subject()
   })
]
```

and maybe also

```
mocks: [
   [ServiceWithObservable, {
      obs$: new Subject()
   }]
]
```

**Comment by NetanelBasal** [comment]
The second example will introduce a breaking change.

**Comment by MartinNuc** [comment]
I think we could support both original and new way to provide mocks. Even combined:

```
mocks: [
   SomeService,
   [ServiceWithObservable, {
      obs$: new Subject()
   }]
]
```

**Comment by NetanelBasal** [comment]
We cannot count on this as Angular supports passing arrays also. The following code will work:

```ts
 imports: [ [module], [module]],
providers: [ [provider ], [provider]]
```

**Comment by MartinNuc** [comment]
You're right. I didnt know that. Ok I will stick to modifying `mockProvider` only.

**Comment by NetanelBasal** [comment]
v3.1.0

**Comment by jkyoutsey** [comment]
I have 3.1.7 and am trying the following
```
		providers: [
			{ provide: Router, useClass: MockRouter },
			mockProvider(DomEventObservablesService, {
				getObservable: new Subject<boolean>()
			})
		],
```
And I get an error that it cannot call `subscribe` on undefined when calling getObservable.

**Comment by MartinNuc** [comment]
Its for properties. Not methods.

If you are trying to mock a method either use jasmine or use ‘getObservable: () => of()’ in mock provider.

**Comment by MrBra1nwash** [comment]
Is there any easier way to mock properties in the spectator? I am using angular + facades. So often I have
```
export class MyFacade {
    someId$ = this.store.select(selectData.getId)
  ...
}
```

And if I want to mock `someId$` in several `it` i should override providers at the beginning of every it like:
```
spectator = createComponentFactory({
      providers: [
         mockProvider(ProjectFacade, {
                someId$: of('test-id'),
          }),
     ]
    });
```

**Comment by NetanelBasal** [comment]
In V4 you can override the component's providers:



```ts
const createProvider = id => mockProvider(ProjectFacade, {
 someId$: of(id),
})

it('should...', () => {
  spectator = createComponent({
    // Override the component's providers
    providers: [createProvider('id')]
  });
});
```
