### ISSUE TITLE
Docs for Jest

### ISSUE THREAD

**Issue by NetanelBasal** [NetanelBasal/spectator#57]
@dirkluijk when you have time.

**Comment by dirkluijk** [comment]
Sure. How can I submit any docs? Can I just submit it in this issue as plain text? 👍

**Comment by NetanelBasal** [comment]
Yes. Write here with markdown and I will transfer it to the gitbook.

**Comment by dirkluijk** [comment]
In "https://netbasal.gitbook.io/spectator/services":

Change:

> The mockProvider() function converts each service method to a jasmine spy. (i.e jasmine.createSpy()).
>
> Here are some of the methods it exposes:
> (code)

Into:

> By default, the `mockProvider()` function converts each service method to a jasmine spy. (i.e jasmine.createSpy()).
>
> Here are some of the methods it exposes:
> (code)
>
> However, if you use Jest as test framework and you want to utilise its mocking mechanism instead, just import the `mockProvider()` from `@netbasal/spectator/jest`. This will automatically use the `jest.fn()` function to create a Jest compatible mock instead.

And maybe it's good to add an additional "Examples" page in the docs, titled "Jest support" (or: "Jasmine vs. Jest":

> # Jest support
> By default, Spectator uses *Jasmine* for creating spies. If you are using *Jest* as test framework instead, you can let Spectator create Jest-compatible spies.
>
> Just import one of the following functions from `@netbasal/spectator/jest` (instead of `@netbasal/spectator`), and it will use Jest instead of Jasmine.
> * `createTestComponentFactory()`
> * `createHostComponentFactory()`
> * `createService()`
> * `createHTTPFactory()`
> * `mockProvider()`
