### ISSUE TITLE
All instances of a MockComponent share the same event emitter, therefore I cannot emit events on individual instances.

### ISSUE THREAD

**Issue by olivlomp** [NetanelBasal/spectator#59]
Hi!

First of, thanks for an awesome testing framework :)

I'm currently mocking some outputs using MockComponent. There seems to be an issue where all instances of the mock component share the same event emitter. Calling emit on a single instance will therefore call the bound method multiple times, once for each instance.

Here's a test to demonstrate this:
```
import { Component, EventEmitter, Output } from "@angular/core";
import { createTestComponentFactory, MockComponent } from "@netbasal/spectator";

@Component({
    selector: "app-subcomponent-component",
    template: ``,
})
class SubcomponentDemoComponent {
    @Output()
    public emitter = new EventEmitter();
}

@Component({
    selector: "app-demo-component",
    template: `
        <app-subcomponent-demo (emitter)="boundMethod()"></app-subcomponent-demo>
        <app-subcomponent-demo (emitter)="boundMethod()"></app-subcomponent-demo>
    `,
})
class DemoComponent {
    public boundMethod() {}
}

describe("spectator", () => {
    const create = createTestComponentFactory({
        component: DemoComponent,
        shallow: true,
        declarations: [
            MockComponent({
                selector: "app-subcomponent-demo",
                identifier: SubcomponentDemoComponent,
                outputs: ["emitter"],
            }),
        ],
    });

    it("should differentiate between instances of event emitters", () => {
        const spectator = create({}, false);
        spyOn(spectator.component, "boundMethod");

        const instances = spectator.queryAll<SubcomponentDemoComponent>(SubcomponentDemoComponent);
        instances[0].emitter.emit();
        expect(spectator.component.boundMethod).toHaveBeenCalledTimes(1);
    });
});
```

The function, boundMethod should only be called once because only one value is emitted, however, it is called twice.

Could you have a look into this?

Thanks and cheers,
Oliver

**Comment by NetanelBasal** [comment]
I see what the problem. It's because it's on the prototype. I think we should move to the complete implementation of Mocks in Angular. 

https://github.com/ike18t/ng-mocks

We're already using it actually in our code. It auto mocks the inputs, outputs, etc.

**Comment by NetanelBasal** [comment]
Yes, this is working as expected:

```ts
import { createTestComponentFactory } from '@netbasal/spectator';
import { MockComponentEmittersComponent } from './mock-component-emitters.component';
import { AppSubcomponentDemoComponent } from '../app-subcomponent-demo/app-subcomponent-demo.component';
import { MockComponent } from 'ng-mocks';

fdescribe('spectator', () => {
  const create = createTestComponentFactory({
    component: MockComponentEmittersComponent,
    shallow: true,
    detectChanges: false,
    declarations: [MockComponent(AppSubcomponentDemoComponent)]
  });

  it('should differentiate between instances of event emitters', () => {
    const spectator = create();
    spyOn(spectator.component, 'boundMethod');

    const instances = spectator.queryAll<AppSubcomponentDemoComponent>(MockComponent(AppSubcomponentDemoComponent));

    instances[0].emitter.emit();
    expect(spectator.component.boundMethod).toHaveBeenCalledTimes(1);
  });
});

```

**Comment by NetanelBasal** [comment]
@dirkluijk for your knowledge.

**Comment by dirkluijk** [comment]
Nice library @NetanelBasal. Maybe I have some time left the next days to submit a PR to integrate it. 😄

**Comment by NetanelBasal** [comment]
We need the Jest docs first :)

**Comment by dirkluijk** [comment]
Of course. By the way, if `ng-mocks` is preferred over the Spectator `MockComponent`, does that mean that no integration is needed at all and that we just have to deprecate the current implementation? Or what do you suggest?

**Comment by NetanelBasal** [comment]
Yes, that's what we did in our application. We're using ng-mocks directly; it's much more comfortable.

**Comment by dirkluijk** [comment]
All right, maybe it's good to update the docs accordingly (and deprecate the Spectator one, and update the existing unit tests to properly demonstrate this compatibility).

**Comment by dirkluijk** [comment]
New doc proposal for: https://netbasal.gitbook.io/spectator/components/untitled-1 (Mock Components).

> # Mock Components
>
> Sometimes it's helpful to pass a mock implementation of other components. You can mock components using the [ng-mocks](https://github.com/ike18t/ng-mocks) library:
> ```typescript
> import { createHostComponentFactory } from '@netbasal/spectator';
> import { MockComponent } from 'ng-mocks';
> 
> import { FooComponent } from './path/to/foo.component';
> 
> const createHost = createHostComponentFactory({
>   component: SettingsPanelComponent,
>    declarations: [
>      MockComponent(FooComponent)
>    ]
>  });
> ```
> For more info about mocking components, please take a look at the `ng-mocks` [docs](https://github.com/ike18t/ng-mocks).

**Comment by olivlomp** [comment]
Hey all, thanks for the quick responses and the swift resolution and clarification! 🥇

**Comment by ike18t** [comment]
I came across this lib after reading @NetanelBasal 's medium article. I'm stoked that you guys are going to pull in ng-mocks. Let me know if there is anything you guys need from me.

**Comment by NetanelBasal** [comment]
@ike18t Yes, we are using ng-mocks. Spectator and ng-mocks together are a win-win :)

**Comment by ike18t** [comment]
I noticed in the spectator docs for mocking a component there is the following line
`const instances = spectator.queryAll<SubComponent>(MockComponent(SubComponent));`

That call to MockComponent isn't necessary since this commit:  
https://github.com/ike18t/ng-mocks/commit/7ccd3f53cd31ffa9055d0da0e7a34952652ade5a#diff-e618e42c87439e062f6fc60c40d0e5abR37

My bad for not representing that in the README, I just updated it.

It can be:
`const instances = spectator.queryAll<SubComponent>(SubComponent);`

That being said you can possibly update your method sig for the query methods from:
`query<R>(directiveOrSelector: Type<any>` to `query<R>(directiveOrSelector: R`
and get the usage down to:
`const instances = spectator.queryAll(SubComponent);`

**Comment by NetanelBasal** [comment]
Awesome!

**Comment by maxime1992** [comment]
> Yes, we are using ng-mocks. Spectator and ng-mocks together are a win-win :)

This has been really useful but it's nowhere in the doc. It'd be a nice addition to the readme I think

**Comment by NetanelBasal** [comment]
@maxime1992 would love to see a PR.

**Comment by maxime1992** [comment]
:point_up_2: https://github.com/ngneat/spectator/pull/206
