### ISSUE TITLE
Missing Type Definition File for @types/je st

### ISSUE THREAD

**Issue by claboran** [NetanelBasal/spectator#63]
Created new angular-cli version 7 project and did a test drive using Spectator.
Received an error when running ng test:
 
ERROR in node_modules/@netbasal/spectator/lib/mock.d.ts(1,23): error TS2688: Cannot find type definition file for '@types/jest'.

Installing @types/jest does not help, since I have inference with jasmine types (want to stick to Jasmine)

Any help is appreciated

**Comment by NetanelBasal** [comment]
@LayZeeDK @dirkluijk any suggestions?

**Comment by claboran** [comment]
@NetanelBasal: Problem has been solved. After adding @types/jest to devDependencies and changing:
`    "types": [
      "jasmine",
      "node"
    ]
`
to
`
    "types": [
      "jest",
      "node"
    ]
` 
in tsconfig.spec.json

**Comment by NetanelBasal** [comment]
Cool, thanks!

**Comment by DmitryEfimenko** [comment]
is that the suggested solution even if not using Jest?

**Comment by claboran** [comment]
My initial setup with angular-cli 7.0.0 and npm install @netbasal/spectator --save-dev
gives:
`ERROR in node_modules/@netbasal/spectator/lib/mock.d.ts(1,23): error TS2688: Cannot find type definition file for '@types/jest'.
// what is obvious
/// <reference types="@types/jest" />
import { Provider, Type } from '@angular/core';
import { SpyObject as BaseSpyObject } from '@netbasal/spectator';
export declare type SpyObject<T> = BaseSpyObject<T> & {
    [P in keyof T]: T[P] & jest.Mock<T>; // <- Here is the problem
};
export declare function createSpyObject<T>(type: Type<T>, template?: Partial<Record<keyof T, any>>): SpyObject<T>;
export declare function mockProvider<T>(type: Type<T>, properties?: Partial<Record<keyof T, any>>): Provider;
`
adding @types/jest
npm install --save-dev @types/jest
running ng test
gives:
`ERROR in node_modules/@types/jasmine/index.d.ts(21,1): error TS6200: Definitions of the following identifiers conflict with those in another file: describe, fdescribe, xdescribe, it, fit, xit, beforeEach, afterEach, beforeAll, afterAll, expect, clock, CustomEqualityTester, CustomMatcherFactory, DEFAULT_TIMEOUT_INTERVAL
node_modules/@types/jasmine/index.d.ts(185,9): error TS2375: Duplicate number index signature.
node_modules/@types/jasmine/index.d.ts(188,15): error TS2428: All declarations of 'ArrayContaining' must have identical type parameters.
node_modules/@types/jasmine/index.d.ts(195,15): error TS2428: All declarations of 'ObjectContaining' must have identical type parameters.
node_modules/@types/jasmine/index.d.ts(238,9): error TS2374: Duplicate string index signature.
node_modules/@types/jasmine/index.d.ts(243,9): error TS2687: All declarations of 'message' must have identical modifiers.
node_modules/@types/jasmine/index.d.ts(243,9): error TS2717: Subsequent property declarations must have the same type.  Property 'message' must be of type 'string | (() => string)', but here has type 'string'.
node_modules/@types/jest/index.d.ts(23,1): error TS6200: Definitions of the following identifiers conflict with those in another file: describe, fdescribe, xdescribe, it, fit, xit, beforeEach, afterEach, beforeAll, afterAll, expect, clock, CustomEqualityTester, CustomMatcherFactory, DEFAULT_TIMEOUT_INTERVAL
node_modules/@types/jest/index.d.ts(990,46): error TS2314: Generic type 'ArrayContaining<T>' requires 1 type argument(s).
node_modules/@types/jest/index.d.ts(991,45): error TS2314: Generic type 'ObjectContaining<T>' requires 1 type argument(s).
node_modules/@types/jest/index.d.ts(1017,15): error TS2428: All declarations of 'ArrayContaining' must have identical type parameters.
node_modules/@types/jest/index.d.ts(1023,15): error TS2428: All declarations of 'ObjectContaining' must have identical type parameters.
`
after changing
`    "types": [
      "jasmine",
      "node"
    ]
`
to
`    "types": [
      "jest",
      "node"
    ]
`
in tsconfig.spec.json

does solve all the errors above.

Do I miss something?

**Comment by DmitryEfimenko** [comment]
@claboran  no, your workaround works. I verified it. However, that's a workaround. The developer should not receive the error after running `npm install @netbasal/spectator --save-dev`.
It should just work.

I think this issue should be re-opened untill there is a proper fix in place (@NetanelBasal ).

**Comment by NetanelBasal** [comment]
I created a new Angular project with cli, installed Spectator, run the tests, and I don't get any error, do I miss something, guys?

**Comment by dirkluijk** [comment]
I can reproduce it as well. I will investigate this immediately, as this is breaking.

**Comment by dirkluijk** [comment]
The problem is as follows:

When building the Spectator lib, it uses (and includes!) Jest typings (for the whole project) because it can't use both Jasmine and Jest typings at the same time (`Definitions of the following identifiers conflict...`).

But developers should be able to use Spectator _without_ having to import Jest's typings. I am now looking for a way to solve this. It would be solved if I can use a different `tsconfig.json` for the secondary entry point.

**Comment by NetanelBasal** [comment]
Thanks, @dirkluijk, I will try to help when I have time.

**Comment by dirkluijk** [comment]
No succes yet. I tried this:

`tsconfig.json`
```
{
  ...
  "types": [],
}
```

`public_api.ts`
```typescript
/// <reference types="@types/jasmine" />

// ...
```

`jest/public_api.ts`
```typescript
/// <reference types="@types/jest" />

// ...
```

But this still conflicts as ng-packagr builds them with the same typescript compiler instance. Will look for other workarounds. Would be nice when jest typings are not conflicting with jasmine.

**Comment by dirkluijk** [comment]
I have a possible fix: https://github.com/dirkluijk/spectator/commit/6a3f63b2fcd1639dbf078104693740a88868e632.

However, in my test app I get this weird error when using Spectator: 

```
Chrome 71.0.3578 (Mac OS X 10.14.0) AppComponent should have as title 'testje-spectator' FAILED
        Failed: Cannot read property 'injector' of null
        TypeError: Cannot read property 'injector' of null
            at TestBedViewEngine.push.../spectator/node_modules/@angular/core/fesm5/testing.js.TestBedViewEngine._createCompilerAndModule (http://localhost:9876/spectator/node_modules/@angular/core/fesm5/testing.js?:1724:1)
            at TestBedViewEngine.push.../spectator/node_modules/@angular/core/fesm5/testing.js.TestBedViewEngine.compileComponents (http://localhost:9876/spectator/node_modules/@angular/core/fesm5/testing.js?:1637:1)
            at Function.push.../spectator/node_modules/@angular/core/fesm5/testing.js.TestBedViewEngine.compileComponents (http://localhost:9876/spectator/node_modules/@angular/core/fesm5/testing.js?:1497:56)
...
```
I have no idea what causes this. Someone?

**Comment by NetanelBasal** [comment]
Need to see it live. You've only changed typings, weird 🤔.

**Comment by dirkluijk** [comment]
Nice. Just found out that the error was caused by `yarn link` 🤷‍♂️ . The fix works perfect. I will submit it as a PR.
