### ISSUE TITLE
HttpFactory expectOne failing when params send with GET request

### ISSUE THREAD

**Issue by FrankMerema** [NetanelBasal/spectator#65]
For a filter endpoint I have to add query params to a GET request.
Before this `expectOne('endpoint/to/call', HTTPMethod.GET)` was working great, but now I have added params to the request and suddenly it stops working and logs ` Expected one matching request for criteria "Match method: GET, URL: 'endpoint/to/call", found none.`. I also see a logging line saying ` Expected no open requests, found 1: GET endpoint/to/call`

The HTTP call before:
```
return this.http.get<SomeObject>(`endpoint/to/call`);
```

The HTTP call after:
```
const params = new HttpParams({
    fromString: 'value1=test&value2=testing'
  });
return this.http.get<SomeObject>(`endpoint/to/call`, {params: params});
```

Thanks!

**Comment by Tre665** [comment]
I have the exact same Issue. Currently we plan to switch to move to spectator and thought it was a mistake on our side.

**Comment by NetanelBasal** [comment]
Can you reproduce on stackblitz, please?

**Comment by NetanelBasal** [comment]
I think it should be `expectOne('endpoint/to/call?value1=test&value2=testing', HTTPMethod.GET)`

**Comment by FrankMerema** [comment]
Do you have a plain playground on Stackblitz I can use for starting?

And I tried the expectOne with query params but still doesn't match...

**Comment by NetanelBasal** [comment]
https://stackblitz.com/edit/angular-testing-spectator?file=app%2Fhello.component.ts

**Comment by FrankMerema** [comment]
I have created the example and your suggestion was correct, you need to add it to the url you expect:

https://stackblitz.com/edit/angular-testing-spectator-http-param-bug

Thanks for the quick reply and solution! Keep up the  good work :)

**Comment by NetanelBasal** [comment]
The first spec isn't right, remove it.
