### ISSUE TITLE
host.query doesnt work for directives

### ISSUE THREAD

**Issue by MartinNuc** [NetanelBasal/spectator#66]
When testing a directive according to https://netbasal.gitbook.io/spectator/directives the `host.query` doesn't work because it expects to have [debugElement](https://github.com/NetanelBasal/spectator/blob/2f70012dfd82d9d26facc794fc780fc102df4166/projects/spectator/src/lib/internals.ts#L97) which is not defined for a directive.

Results in `TypeError: Cannot read property 'query' of null` with stack trace:

```
    at <Jasmine>
    at http://localhost:9877/node_modules/@netbasal/spectator/fesm5/netbasal-spectator.js?:896:1
    at SpectatorWithHost.push../node_modules/@netbasal/spectator/fesm5/netbasal-spectator.js.Spectator.query (http://localhost:9877/node_modules/@netbasal/spectator/fesm5/netbasal-spectator.js?:517:1)
```

*Possible solution*: use `hostDebugElement` when `debugElement` is not defined.

What do you think?

**Comment by NetanelBasal** [comment]
Yes, you need to use the hostDebugElement when testing directives.

**Comment by MartinNuc** [comment]
What I am suggesting is to change the `query` method to use `hostDebugElement` when the `debugElement` is not defined. What do you think?

**Comment by MartinNuc** [comment]
I am digging deeper to fix those types and it looks like I made fix it on a wrong place. There should be nothing related to host in the parent `Spectator` class. Instead it needs fix in `SpectatorWithHost`. Sorry about that. Fix is on the way :-)

**Comment by NetanelBasal** [comment]
Yes, that's OK, I should have noticed too.
