### ISSUE TITLE
Document mocking ngrx store

### ISSUE THREAD

**Issue by jkyoutsey** [NetanelBasal/spectator#67]
You should document how to mock ngrx store in a component/service.

Here is an example of how to mock the store in a service where the service needs data from selectors for a small slice of the store state.  I'd love to know if there is a way to simplify this even more...

```
import { SearchService } from './search.service';
import { createService } from '@netbasal/spectator';
import { of } from 'rxjs';
import { StoreModule, Action } from '@ngrx/store';
import * as fromBook from '@book/state';

function reducer(state = {}, action: Action): {} {
  switch (action.type) {
    default:
      return state;
  }
}

describe('SearchService', () => {
  const spectator = createService({
    service: SearchService,
    imports: [
      StoreModule.forRoot(reducer),
      StoreModule.forFeature('book', fromBook.reducer)
    ]
  });

  beforeEach(() => {
    // const store = spectator.get(Store) just returns {} ???
    // Grab the private instance of the store in the service under test:
    const store = spectator.service['store'];
    store.dispatch(new fromBook.SetCurrentBookId(42));
    store.dispatch(new fromBook.SetCurrentProductId(1));
  });

  it('can search', () => {
    const testData = {};
    const spy = spyOn(myObject, 'someMethod').and.returnValue(of(testData));
    spectator.service.search('something');
    expect(spy).toHaveBeenCalledWith(42, 1, true, true);
  });

});
```

**Comment by NetanelBasal** [comment]
Thanks for the suggestion but we can't document one specific library. What about ngxs, Akita, mobx, etc. If someone asks, I will redirect to this issue. Thanks.

**Comment by schmkr** [comment]
Stumbled upon this issue while searching how to use spectator with ngxs. Not only to mock its store in components under test, but the actual store itself?

The ngxs schematics generate this boilerplate by default:

```typescript
let store: Store;
beforeEach(async(() => {
  TestBed.configureTestingModule({
    imports: [NgxsModule.forRoot([AuthState])]
  }).compileComponents();
  store = TestBed.get(Store);
}));
```

So my feeling would be that spectator's `createTestComponentFactory` function could somehow be used for this, but what would be the component the function needs as a parameter?

**Comment by schmkr** [comment]
After asking in the ngxs Slack if anyone had any experience with this, there was noone that actually did, but one person replied

> Remember that the state is just a object constant.

That got me thinking, isn't _that_ the same for all other libraries (ngrx, mobx, Akita)? I am not sure, but if that is the case, would it be possible, or is there any recommendation, on how to set up such object constants for testing with Spectator? Maybe by providing a similar function like `createHostComponentFactory` and `createService`, but then `createConstant`? Or maybe documenting how to achieve this with `createService`?

**Comment by NetanelBasal** [comment]
How would you do that without spectator?

**Comment by schmkr** [comment]
Yesterday, thanks to the documentation on this page https://netbasal.gitbook.io/spectator/services and the chapter about Typed Mocks, I managed to use that for testing both a NGXS state and an Angular Guard. 

```ts 
//auth.guard.spec.ts
import { TestBed } from '@angular/core/testing';
import { SpyObject, mockProvider } from '@netbasal/spectator';

import { AuthGuard } from './auth.guard';
import { AuthService } from './auth.service';

describe('AuthGuard', () => {
    let authService: SpyObject<AuthService>;
    let guard: AuthGuard;

    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [
                AuthGuard,
                mockProvider(AuthService)
            ],
        });

        guard = TestBed.get(AuthGuard);
        authService = TestBed.get(AuthService);
    });

    it('should ...', () => {
        expect(guard).toBeTruthy();
    });
});
```

I think I tried too hard to use `createService` or `createTestComponentFactory` or `createHostComponentFactory`.

**Comment by SachinShekhar** [comment]
NgRx officially provides `MockStore` in `@ngrx/store/testing` which even has method to override selectors.

https://ngrx.io/guide/store/testing

**Comment by f4irline** [comment]
> NgRx officially provides `MockStore` in `@ngrx/store/testing` which even has method to override selectors.
> 
> https://ngrx.io/guide/store/testing

Sure, but how do you use it with Spectator?

**Comment by jmbeach** [comment]
I think I figured this out, but not sure if it's good practice. 

I'm creating an AppComponent spectator that imports the the store/reducers

```ts
const createComponent = createComponentFactory({
  component: AppComponent,
  imports: [
    StoreModule.forRoot({
      ...fromRoot.reducers,
      products: combineReducers(reducers)
    })
  ],
  shallow: true
});

let spectator: Spectator<AppComponent>;
```

I get the store off of the app component.

```ts
let dispatchSpy: jest.SpyInstance;

beforeEach(() => {
  spectator = createComponent()
  // bad practice 🤷 ?
  store = (spectator.component as any).store as Store<ProductsState>;
  dispatchSpy = jest.spyOn(store, 'dispatch');
})
```

because my AppComponent looks like this:

```
export class AppComponent implements OnInit {
  constructor (private store: Store) {}
}
```

Reading a private property doesn't feel great, but idk. It's just for testing.

And then my tests look like this:

```ts
describe('getToppingEntitites', () => {
  it('should return toppings as entities', async () => {
    let value: any = await store.select(getToppingsEntities).pipe(take(1)).toPromise();
    expect(value).toEqual({});
    store.dispatch(new LoadToppingsSuccess(toppings))
    value = (await store.select(getToppingsEntities).pipe(take(1)).toPromise())
    expect(value[toppings[0]?.id as any]).toEqual(toppings[0]);
  })
})
```
