### ISSUE TITLE
createService doesn't accept declarations

### ISSUE THREAD

**Issue by MartinNuc** [NetanelBasal/spectator#68]
At first glance it makes perfect sense that `createService` doesn't need declarations array however when testing a service depending on `RouterModule` there is a need to define routes. And routes must lead to a component.

I could mock `Router` and that would solve my problem. However that means also mimicking internal behaviour of `Router`.

What do you think about allowing `declarations` also for `createService`?

**Comment by NetanelBasal** [comment]
Why do you need the router in services? Why not mock it? I'm guessing you aren't testing the router implementation.

**Comment by MartinNuc** [comment]
I think my problem is mixing unit tests (there you mock `Router`) and integration tests (there you try to use `RouterTestingModule`). I use TestBed (and therefore Spectator) for both.

How do you write integration tests?

**Comment by NetanelBasal** [comment]
I don't :). I have no problem adding your suggestion.

**Comment by MartinNuc** [comment]
Let me do research how people write integration tests in Angular first :-)

**Comment by MartinNuc** [comment]
In documentation there is only one note about integration tests: https://angular.io/guide/testing#when-would-i-put-specs-in-a-test-folder

I also found an article saying that we should place integration tests in a file with special name `*.integration.spec.ts`: https://christianlydemann.com/complete-guide-to-angular-testing/

But there is no recommended way how to write them.

If we wanted to avoid mocking and mimicking the whole Router we really need that `RouterTestingModule`.

Therefore if you dont mind I will create PR which allows `declarations` also for `createService`.

**Comment by NetanelBasal** [comment]
No problem.

**Comment by MartinNuc** [comment]
Tried to prepare test of a service integrating with `Router` just by listening to `router.events` but it doesn't emit anything. So I guess `RouterTestingModule` contains some kind of incomplete mock of Router.

I didn't come up with another case of using `declarations` array for a service than integration with router so I will close this issue and we can reopen it when another case comes up.

I was also considering a service using a dynamic component from `entryComponents` but that doesn't related to `declarations` either.

**Comment by MartinNuc** [comment]
New issue here: https://github.com/NetanelBasal/spectator/issues/106
