### ISSUE TITLE
Suggestion: toBeEmpty() should ignore comment nodes

### ISSUE THREAD

**Issue by fr0** [NetanelBasal/spectator#7]
I'm using `toBeEmpty()` to ensure that an element with a sub-element that has either an `*ngFor` or an `*ngIf` contains no children, but both of those directives add a comment node to the DOM, which causes `toBeEmpty()` to return `false`.

If you don't like this idea, maybe adding another matcher that has this behavior is a better alternative.

**Comment by NetanelBasal** [comment]
makes sense to me. Will add it. Thanks!

**Comment by NetanelBasal** [comment]
When you test ngIf you should use `toExist()`.

**Comment by NetanelBasal** [comment]
Closing for now, if you have an issue with `toExist()` reopen it.
