### ISSUE TITLE
expectOne: Spec has no expectations

### ISSUE THREAD

**Issue by MartinNuc** [NetanelBasal/spectator#75]
When testing data service using `createHTTPFactory` I see errors in the console saying that the test has no expectations. Looks like `expectOne` is not connected to jasmine.

Simple fix would be to add `expect(true).toBe(true);` to `expectOne` but I am not sure if it's the correct one.

Tried with spectator 3.3.0 but it behaved same with the older version.

**Comment by NetanelBasal** [comment]
We fixed that by monkey patching `console.error` and exclude this type of error.

**Comment by NetanelBasal** [comment]
https://github.com/dfederm/karma-jasmine-html-reporter/issues/20

**Comment by MartinNuc** [comment]
ehhhh, monkeypatching `console.error` doesn't look like a good solution either :-(

What do you think about adding `expect(true).toBe(true)` to this place? https://github.com/NetanelBasal/spectator/blob/7ae901860704ce50f26f7753b6d6101e83761b2b/projects/spectator/src/lib/http.ts#L52

Using `expectOne` is like running expect so ⤴️ could workaround the issue.

**Comment by NetanelBasal** [comment]
Sounds like a good idea.
