### ISSUE TITLE
Configure type auto completion for IDE

### ISSUE THREAD

**Issue by AhnpGit** [NetanelBasal/spectator#8]
Hi,

I want to configure typing autocompletion when using your library but I couldn't find anything in the README. Would you please tell me how to configure it ?

**Comment by NetanelBasal** [comment]
You should get autocompletion. It's written in typescript.

**Comment by AhnpGit** [comment]
hmm I think because I was using Jest and @types/jest instead of jasmine, that was why IDE didn't suggest any code completions. I already found a workaround that I declare a namespace jest inside typings.d.ts similar to your typing declarations.

**Comment by NetanelBasal** [comment]
The library does not support jest. It's for jasmine.

**Comment by AhnpGit** [comment]
thank you for your reply. Even though it supports for jasmine but it also works with jest. I tested it with my repo. That made me happy 👍
