### ISSUE TITLE
Question: MockDirective structural directives

### ISSUE THREAD

**Issue by tamasfoldi** [NetanelBasal/spectator#81]
Is it possible to use MockDirective for structural directives somehow?

**Comment by NetanelBasal** [comment]
Use https://github.com/ike18t/ng-mocks.

**Comment by tamasfoldi** [comment]
If that package is the recommended one, shouldn't be better to remove Spectator's MockDirective from the public API?

**Comment by NetanelBasal** [comment]
It's deprecated. We'll remove it in the next major release.
