### ISSUE TITLE
Spectator command hanging indefinitely

### ISSUE THREAD

**Issue by IlCallo** [NetanelBasal/spectator#83]
When I launch `spectator` command and answer all questions, the CLI "hangs" and never return control to me. I'm forced to kill it and restart.

I'm on Windows 10, using Git Bash via VSCode.
If there be more useful info you could need to solve the problem, I'll be happy to provide them.

**Comment by NetanelBasal** [comment]
We should upgrade plop. Btw, you can use the new schematics now.

**Comment by IlCallo** [comment]
I'll try it out, thanks

**Comment by IlCallo** [comment]
Tested and now everything works as expected, thanks!
