### ISSUE TITLE
Spectator does nothing when a spec file already exists

### ISSUE THREAD

**Issue by IlCallo** [NetanelBasal/spectator#84]
I'm starting to use Spectacular on an existing codebase, so most components already have a spec file, even if some of them are just the pregenerated ones.

If I try to use `spectator` for those components, no spec file is created.

I would expect an overwrite confirmation prompt or a `-f/--force` or `-o/--overwrite` option to manage this kind of situation. What do you think about this?

**Comment by NetanelBasal** [comment]
Sounds good. It should be managed by spectator-cli that works with plop.

**Comment by NetanelBasal** [comment]
If you want to submit a PR, here's the source code: https://github.com/NetanelBasal/spectator-cli/blob/master/plopfile.js

You should upgrade plop to solve the first issue and look for a `force` option in plop API.

**Comment by IlCallo** [comment]
I'll try to work on a PR, even if I don't know exactly when

**Comment by IlCallo** [comment]
I found a [small paragraph](https://github.com/amwmedia/plop#running-a-generator-forcefully) on this, but it's supported from version 2 onwards.
It's a major version update (1.9.1  => 2.3.0) because they dropped support for Node 4.
Shall I update other dependencies as well?

**Comment by NetanelBasal** [comment]
Yes, you can.

**Comment by IlCallo** [comment]
Still not found a way to make it automatically ask for overwrite confirmation, but after dependencies update it prints a line specifying that the file has been skipped because it already exists.
Until plop itself support confirmation prompt, that's enough for me I guess.

Ty anyway!
