### ISSUE TITLE
query by directive throws error when nothing is found

### ISSUE THREAD

**Issue by MartinNuc** [NetanelBasal/spectator#85]
I was trying to write a test which checks that a component is missing (hidden by `*ngIf`). I used [query by type](https://netbasal.gitbook.io/spectator/api/queries) which uses `By.directive` internally.

However when the component is not found it throws an exception [here](https://github.com/NetanelBasal/spectator/blob/f9ef2a527945f4503e2f0459d557fc9d0d77284d/projects/spectator/src/lib/internals.ts#L307).

This throwing method is called from [query](https://github.com/NetanelBasal/spectator/blob/f9ef2a527945f4503e2f0459d557fc9d0d77284d/projects/spectator/src/lib/internals.ts#L73).

I would like to suggest to catch this exception in `query` and return `null` instead. What do you think?

**Comment by NetanelBasal** [comment]
Sounds good to me.

**Comment by MartinNuc** [comment]
Ok, I will make PR tomorrow :) thanks
