### ISSUE TITLE
Mocking service methods with mockProvider()

### ISSUE THREAD

**Issue by ruimarques** [NetanelBasal/spectator#88]
This might be a bug with `mockProvider()` of maybe I don't fully understand it. The documentation does say its second parameter is to mock properties but I expected it to mock methods also.

While testing a component:

```javascript
describe('SomeComponent', () => {

  const SomeServiceMock = {
    requestData: () => of({}),
  };

  // This way - mocks the service as expected but no spies are attached
  const createComponent = createTestComponentFactory({
    component: ButtonComponent,
    providers: [
      { provide: SomeService, useValue: SomeServiceMock }
    ]
  });

  // This way - TypeError: Cannot read property 'pipe' of null
  const createComponent = createTestComponentFactory({
    component: ButtonComponent,
    providers: [
      mockProvider(SomeService, SomeServiceMock),
    ]
  });

  it('should create', () => {
    spectator = createComponent();

    expect(spectator.component).toBeTruthy();
  });
});

class ButtonComponent implements OnInit {
  constructor(someService: SomeService) { }
  ngOnInit() {
    this.someService.requestData().pipe(map(data => data)).subscribe();
  }
}
```

Seems similar to what was mentioned here https://github.com/NetanelBasal/spectator/issues/56#issuecomment-470254813

**Comment by NetanelBasal** [comment]
It should. @MartinNuc can you clarify, please?

**Comment by NetanelBasal** [comment]
It's mock the methods. You will get a spy, and you need to return what you need, for example:

`this.someService.requestData.and.returnValue(of(value))`

**Comment by MartinNuc** [comment]
@ruimarques it's not possible for methods unfortunately because methods are overriden. But this is second question regarding this topic so I will make a PR to change this so its possible to define methods using 2nd argument.

**Comment by NetanelBasal** [comment]
@MartinNuc do you mean class properties that are functions?

**Comment by MartinNuc** [comment]
Yes. I will change the implementation to create a method mock only when it's not defined in the 2nd parameter object. Should be easy change.

**Comment by ruimarques** [comment]
Awesome work guys!

Personally I would find it useful that mocked methods have a spy attached, do you think it would be useful for more people?

My current work around this is to do the following for each method I need a spy:

```javascript
const someServiceMock = {
    get: () => of({})
 };

 const createComponent = createTestComponentFactory({
    component: SomeComponent,
    providers: [
      mockProvider(SomeService, someServiceMock),
   ]
  });

  beforeEach(() => {
    spyOn(someServiceMock, 'get').and.callThrough();

    spectator = createComponent();
  });
```

**Comment by sashissd** [comment]
> Awesome work guys!
> 
> Personally I would find it useful that mocked methods have a spy attached, do you think it would be useful for more people?
> 
> My current work around this is to do the following for each method I need a spy:
> 
> ```js
> const someServiceMock = {
>     get: () => of({})
>  };
> 
>  const createComponent = createTestComponentFactory({
>     component: SomeComponent,
>     providers: [
>       mockProvider(SomeService, someServiceMock),
>    ]
>   });
> 
>   beforeEach(() => {
>     spyOn(someServiceMock, 'get').and.callThrough();
> 
>     spectator = createComponent();
>   });
> ```

Thanks Mate..
