### ISSUE TITLE
dispatchKeyboardEvent doesn't work as expected

### ISSUE THREAD

**Issue by bengry** [NetanelBasal/spectator#9]
Adding the following to `ZippyComponent`:
```html
<div (click)="toggle()" class="zippy__title" (keyup.enter)="toggle()">
```

and adding the following test:
```typescript
it('should toggle the content when pressing "Enter"', () => {
    host = createHost(`<zippy title="Zippy title"></zippy>`);

    const pressEnter = () => {
      host.dispatchKeyboardEvent('.zippy__title', 'keyup', /* Enter key */ 13);
    };

    pressEnter();
    expect(host.query(".zippy__content")).toExist();

    pressEnter();
    expect(".zippy__content").not.toExist();
  });
```

Will **fail**, though it's expected to **succeed**.

The following alternative code in (plain) Angular **works** (notice the differences in the `pressEnter` function):
```typescript
it('should toggle the content when pressing "Enter"', () => {
    host = createHost(`<zippy title="Zippy title"></zippy>`);

    const pressEnter = () => {
      host.getNativeElement('.zippy__title').dispatchEvent(new KeyboardEvent('keyup', { key: 'Enter' }));
      host.detectChanges();
    };

    pressEnter();
    expect(host.query(".zippy__content")).toExist();

    pressEnter();
    expect(".zippy__content").not.toExist();
  });
```

**Comment by bengry** [comment]
I'm not sure, but it's not an issue with Spectator as much as its a logical issue in general.
The recommended way is to pass the `key` and not a `keyCode`, since the former conveys the logical meaning which the latter the physical key. e.g. the "regular" `ENTER` key has a different keyCode than the `NUMPAD ENTER` key.

**Comment by NetanelBasal** [comment]
I also making `getNativeElement()` private, It's only for internal use.
