### ISSUE TITLE
components with custom host

### ISSUE THREAD

**Issue by elena-dev-thought** [NetanelBasal/spectator#99]
**Question:**
What is the difference when creating a component with input this way (which for me seems to be easier and less boiler plate as I don't have to mock another input component.)
Am I missing something?

`
  let host: SpectatorWithHost<GooglePlaceDetailComponent>;
  host = createHost(
      `<app-place-detail></app-place-detail>`,
      true,
      {
        placeItem: placeItemMock as any
      }
    );`

versus the solution described in the documentation
` let host: SpectatorWithHost<ZippyComponent, CustomHostComponent>;

  const createHost = createHostComponentFactory({
    component: ZippyComponent,
    host: CustomHostComponent
  });`

P.S.: "I love this testing library <3"

**Comment by dirkluijk** [comment]
There is not a iron rule, it depends.

Personally:
- I use `Spectator` (`createTestComponentFactory`) when I **don't** want to test the interaction with a parent component (`@Input`/`@Output`). For example a routed component.
- I use `SpectatorWithHost` (`createHostComponentFactory`) when I want to test things like inputs, outputs, life-cycle hooks, etc.
- I use a _custom HostComponent_ when I work with complex input/output or just when I want type-safety, because you can add custom properties on the host.  😁 

Does that answer your question?

**Comment by elena-dev-thought** [comment]
Thanks for your answer but what I mean is that case when you have the example with the host.

You can create a custom host to test complex inputs but you can also the normal host creation to test complex inputs. Is there any difference? In my opinion for the custom host I need to write much more code.

```typescript
// using complex input with the normal createHost
host = createHost('<my-component></my-component>', true, { someInput: { ... } } );


// using with the create custom host
@Component(...) myCustomComponent { ... }
...
host = createHost(`<my-component [someInput]="inputFromMyCustomHost"></my-component>`)
```

**Comment by dirkluijk** [comment]
Ok, let me show you. With a custom host, you can do things like this:


```typescript
@Component({
  selector: 'host', template: ''
})
class HostComponent {
  title = 'Foo';
  open = false;
}

describe('ExpansionPanelComponent', () => {
  const createHost = createHostComponentFactory({
    component: ExpansionPanelComponent,
    host: HostComponent
  });

  let host: SpectatorWithHost<ExpansionPanelComponent, HostComponent>;

  beforeEach(() => {
    // use (two-way) bindings to custom properties on our custom host component
    host = createHost('<expansion-panel [title]="title" [(open)]="open"></expansion-panel>');
  });

  it('should toggle', () => {
    expect(host.hostComponent.open).toBe(false);

    host.click('.expansion-panel-header');

    expect(host.hostComponent.open).toBe(true); // <-- check interaction with host
  });
});
```

With the default `HostComponent` of Spectator, which has no properties, you cannot do this. You can only test things like `<expansion-panel [title]="'foo'" [open]="true"></expansion-panel>`. Also, with this custom host, you can add methods or spy functions in a clean and typed way.

**Comment by elena-dev-thought** [comment]
Ok, I think I got it :D So to test outputs you really need the custom host. If I have only Inputs to test, I can go for the third argument in the createHost function.

Thank you!!!
